### DISCUSSION TITLE
Is it possible to use two external linstor clusters at the same time?

### DISCUSSION THREAD

**Discussion by jonathon2nd** [piraeusdatastore/piraeus-operator#689] [Ideas]
Hello!

We are planning some new servers, and we are evaluating having two clusters for HA.
Is it possible to have two `apiVersion: piraeus.io/v1 kind: LinstorCluster` k8s objects for our external linstor clusters, and have some way to have k8s workers 1 2 and 3 use cluster1, and workers 4 5 and 6 use cluster2?

I noticed in `apiVersion: piraeus.io/v1 kind: LinstorSatellite` the following in the yaml

```
spec:
  clusterRef:
    externalController:
      url: >-
        http://10.2.4.10:3370/,http://10.2.4.11:3370/,http://10.2.4.12:3370/,http://10.2.4.13:3370/
    name: linstorcluster
```

So I think it is possible, I have checked linstor doc and not seeing anything.

Our idea would be to have one k8s cluster span these two host clusters (as opposed to using something like liqo)
