### DISCUSSION TITLE
How to use LUKS with LVM?

### DISCUSSION THREAD

**Discussion by cf-sewe** [piraeusdatastore/piraeus-operator#776] [Q&A] [answered]
I have created the K8S secret with `MASTER_PASSPHRASE` and specify it in `LinstorCluster` by `spec.linstorPassphraseSecret`.
But how can I actually add the LUKS layer as described [in the LINSTOR guide](https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-encrypt_commands)?

**Comment by WanzenBug** [comment, marked as answer]
You can set it on the StorageClass in the `layerList` parameter like so:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-encrypted
parameters:
  layerList: "drbd luks storage"
  ...
```
