### ISSUE TITLE
Add podAntiAffinity for cs-controller and csi-controller

### ISSUE THREAD

**Issue by alexzhc** [piraeusdatastore/piraeus-operator#108]
Hi, @WanzenBug 

As cs-controller and csi-controller both may have multiple replicas for HA. It is important to add `podAntiAffinity`, so that pods will land on different nodes. 

For cs-controller, I can do
```
  affinity: 
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - piraeus-controller
          topologyKey: kubernetes.io/hostname
``` 

However csi-controller labels are not that articulated for affinity use: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-02T08:05:18Z"
  generation: 1
  labels:
    app: piraeus-op
  name: piraeus-op-csi-controller
  namespace: storage-system
```

Recommendations: 
1. Add `labels: role: piraeus-csi-controller` for op-csi-controller
2. Make `podAntiAffinity` default for both controllers ?
