### ISSUE TITLE
Resource not being deleted after PVC and PV deletion

### ISSUE THREAD

**Issue by madianas** [piraeusdatastore/piraeus-operator#162]
When PVC and PV gets deleted, ``linstor resource list`` still shows all of the PVC's

My setup:
```
    - helm upgrade piraeus-op ./charts/piraeus
      --install
      --create-namespace
      --namespace piraeus
      --values ./values.yaml
      --set etcd.enabled=false
      --set operator.controller.dbConnectionURL=jdbc:postgresql://10.10.6.5:5432/linstordb?user=linstoruser&password=123
```
Helm Values file:
```
operator:
  replicas: 3
  satelliteSet:
    kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-focal:v9.0.27
    storagePools:
      lvmThinPools:
      - name: lvm-thin-hdd
        thinVolume: thinpoolhdd
        volumeGroup: "linstor_thinpoolhdd"
      - name: lvm-thin-ssd
        thinVolume: thinpoolssd
        volumeGroup: "linstor_thinpoolssd"
  controller:
    replicas: 3
csi:
  enableTopology: true
  controllerReplicas: 3
haController:
  replicas: 3
```

Created custom StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linstor-hdd-r1
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: linstor.csi.linbit.com
parameters:
  allowRemoteVolumeAccess: 'true'
  autoPlace: '1'
  csi.storage.k8s.io/fstype: xfs
  disklessOnRemaining: 'false'
  mountOpts: 'noatime,discard'
  placementPolicy: FollowTopology
  resourceGroup: linstor-hdd-r1
  storagePool: lvm-thin-hdd
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```
Deployed a StatefulSet, it provisions nicely, then completely uninstalled it including namespace.

Linstor still has old Resources:
![image](https://user-images.githubusercontent.com/7828566/106736780-16b78c80-6640-11eb-81cd-7aec60cb8775.png)

Is this expected behavior or a bug or am I doing something wrong?
