### ISSUE TITLE
Monitoring metrics

### ISSUE THREAD

**Issue by Fgruntjes** [piraeusdatastore/piraeus-operator#165]
Hello,

First of thank you for all the hard work that you are putting into this product. We are testing the operator, and managed to set everything up as expected. Only setting up monitoring proves to be problematic. 

Judging from the code in https://github.com/piraeusdatastore/piraeus-operator/blob/e46d5c4d4de6e5c0c0e09eb36c6020798f847623/cmd/manager/main.go#L162 it should create the monitoring.coreos.com/v1/ServiceMonitor resource definitions by itself but for some reason it does not. Also creating a ServiceMonitor manually does not seem to work.

```
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
spec:
  endpoints:
    - port: http-metrics
  namespaceSelector:
    matchNames:
      - infra-storage
  selector:
    matchLabels:
      name: piraeus-operator
```

Could you give me some pointers on what I am doing wrong?

**Comment by WanzenBug** [comment]
To be honest, we haven't really checked if the service monitor sets up correctly. The code you see is just what the operator-sdk sets up automatically.

I suspect that we just don't give the operator service account the needed permissions. You should see some error message in the logs of the operator pod on start up, along the lines of:
```
{"level":"info","ts":1614672080.7990227,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"servicemonitors.monitoring.coreos.com is forbidden: User \"system:serviceaccount:storage:piraeus\" cannot create resource \"servicemonitors\" in API group \"monitoring.coreos.com\" in the namespace \"storage\""}
```
You would need to manually allow this creation using something like the following yaml (unverified!):
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: piraeus-operator-metrics
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create # maybe more?
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: piraeus-operator-metrics
subjects:
  - kind: ServiceAccount
    name: piraeus-operator
roleRef:
  kind: Role
  name: piraeus-operator-metrics
  apiGroup: rbac.authorization.k8s.io
```
and then restart the operator:
```
kubectl -n infra-storage rollout restart deployment piraeus-operator
```

**Comment by Fgruntjes** [comment]
@WanzenBug thank you for your quick response! Just now had the time to test your suggestion, and it worked but only partially.

The service `piraeus-operator-metrics` is created with selector `name=piraeus-operator`. The helm deployment was created as `linstor-operator`. Resulting in a `linstor-operator-piraeus-operator` service name label.

Solved the issue by renaming my helm release to `piraeus`.

**Comment by Fgruntjes** [comment]
FYI we also added two services and service monitors to monitor the etcd and cs resources. Would be great of those could be included into the helm chart.

```yaml
kind: Service
apiVersion: v1
metadata:
    name: piraeus-cs-metrics
    namespace: infra-storage
    labels:
        name: piraeus-cs-metrics
spec:
    ports:
    - name: piraeus-cs
      protocol: TCP
      port: 3370
      targetPort: 3370
    selector:
        app: piraeus-cs
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
    name: piraeus-cs
    namespace: infra-storage
spec:
    endpoints:
    - port: piraeus-cs
    namespaceSelector:
        matchNames:
        - infra-storage
    selector:
        matchLabels:
            name: linstor-cs-metrics
---
kind: Service
apiVersion: v1
metadata:
    name: piraeus-etcd-metrics
    namespace: infra-storage
    labels:
        name: piraeus-etcd-metrics
spec:
    ports:
    - name: piraeus-etcd
      protocol: TCP
      port: 2379
      targetPort: 2379
    selector:
        app: piraeus-etcd
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
    name: piraeus-etcd
    namespace: infra-storage
spec:
    endpoints:
    - port: etcd-client
    namespaceSelector:
        matchNames:
        - infra-storage
    selector:
        matchLabels:
            name: piraeus-etcd-metrics
```
