### ISSUE TITLE
[Feature Request] Arbitrator (DRBD Diskless Quorum) support

### ISSUE THREAD

**Issue by Omar007** [piraeusdatastore/piraeus-operator#183]
DRBD supports the use of an (additional) diskless node to function/assist as an arbitrator in quorum decisions without the need for extra storage.  
With this feature request I'd like to request the Piraeus Operator to be expanded to provide a way to select nodes that should participate as an arbitrator node type.  

This would for instance allow for only two data nodes/replicas with a third DRBD node as a diskless node functioning as the arbitrator for breaking ties and maintaining quorum. (sidenote; an arbitrator node cannot help restore the quorum _after_ it is lost  since it does not have a copy of the data but assisting in maintaining the quorum in the first place should already help a lot for these situations!)

For extra context:
https://linbit.com/blog/cheap-votes-drbd-diskless-quorum/

**Comment by WanzenBug** [comment]
That's actually already possible. You don't _need_ to use the integrated storage pool configuration via the helm chart/CRD, you can also configure them manually and just not assign a storage pool to one of the nodes to act as an arbitrator.

Alternatively, you can create multiple `LinstorSatelliteSet` resources. For example:
```
apiVersion: piraeus.linbit.com/v1
kind: LinstorSatelliteSet
metadata:
  name: piraeus-disk-satellite
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: piraeus.io/node-type
            operator: In
            values:
            - disk
  controllerEndpoint: http://piraeus-op-cs.default.svc:3370
  drbdRepoCred: ""
  kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-centos7:v9.0.29
  kernelModuleInjectionMode: Compile
  kernelModuleInjectionResources: {}
  priorityClassName: ""
  satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.12.3
  storagePools:
    lvmThinPools:
    - devicePaths:
      - /dev/sda
      name: autopool-sda
      thinVolume: autopool-sda
      volumeGroup: ""
---
apiVersion: piraeus.linbit.com/v1
kind: LinstorSatelliteSet
metadata:
  name: piraeus-arbitrator-satellite
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: piraeus.io/node-type
            operator: In
            values:
            - arbitrator
  controllerEndpoint: http://piraeus-op-cs.default.svc:3370
  kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-centos7:v9.0.29
  kernelModuleInjectionMode: Compile
  satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.12.3
  priorityClassName: ""
  drbdRepoCred: ""
```

One set has some storage pools configured, the other does not.

**Comment by Omar007** [comment]
> You don't need to use the integrated storage pool configuration via the helm chart/CRD, you can also configure them manually and just not assign a storage pool to one of the nodes to act as an arbitrator.
I suppose so but the idea of using an operator would normally be to abstract away that manual work and have it be managed by said operator, hence the Feature Request. I am aware manual work would have been possible since the underlying system can already do it, this request was about integrating and automating it basically.

> Alternatively, you can create multiple LinstorSatelliteSet resources. For example:
That is already a way better option than manually configuring it that I did not realise would work/was an option. I'll try this out but if this already works than this can basically be closed I guess. Would be nice to have this added to the docs somewhere in that case though  :+1:

**Comment by Omar007** [comment]
Maybe I'm missing something or it can't work with just an additional LinstorSatelliteSet. The extra node is added and present in the node list but because of the lack of storage pool information, it doesn't look like it's participating in the quorum for anything at all.

**Comment by WanzenBug** [comment]
Did you check with `linstor resource list -a`? The default tiebreaker node is hidden from the default output

**Comment by Omar007** [comment]
I did. The node does not show up there.

**Comment by WanzenBug** [comment]
```
root@vm:~/csi-snap-test# kubectl linstor rg l
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ ResourceGroup                           ┊ SelectFilter                    ┊ VlmNrs ┊ Description ┊
╞══════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltRscGrp                              ┊ PlaceCount: 2                   ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ sc-bd082d42-86af-5398-a8b5-207169a18954 ┊ PlaceCount: 2                   ┊ 0      ┊             ┊
┊                                         ┊ StoragePool(s): autopool-sda    ┊        ┊             ┊
┊                                         ┊ LayerStack: ['DRBD', 'STORAGE'] ┊        ┊             ┊
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
root@vm:~/csi-snap-test# kubectl linstor rd l
╭───────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName                             ┊ Port ┊ ResourceGroup                           ┊ State ┊
╞═══════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ pvc-db6eb0df-29fe-41e0-8b1c-94ec032b3343 ┊ 7001 ┊ sc-bd082d42-86af-5398-a8b5-207169a18954 ┊ ok    ┊
┊ pvc-db67eab4-dbf6-4560-8270-141d0214d70e ┊ 7000 ┊ sc-bd082d42-86af-5398-a8b5-207169a18954 ┊ ok    ┊
╰───────────────────────────────────────────────────────────────────────────────────────────────────╯
root@vm:~/csi-snap-test# kubectl linstor r l
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName                             ┊ Node                  ┊ Port ┊ Usage  ┊ Conns ┊    State ┊ CreatedOn           ┊
╞═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ pvc-db6eb0df-29fe-41e0-8b1c-94ec032b3343 ┊ centos-7-k8s-100.test ┊ 7001 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2021-05-27 10:00:39 ┊
┊ pvc-db6eb0df-29fe-41e0-8b1c-94ec032b3343 ┊ centos-7-k8s-101.test ┊ 7001 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2021-05-27 10:00:40 ┊
┊ pvc-db67eab4-dbf6-4560-8270-141d0214d70e ┊ centos-7-k8s-100.test ┊ 7000 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2021-05-27 10:00:34 ┊
┊ pvc-db67eab4-dbf6-4560-8270-141d0214d70e ┊ centos-7-k8s-101.test ┊ 7000 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2021-05-27 10:00:34 ┊
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
root@vm:~/csi-snap-test# kubectl linstor r l -a
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName                             ┊ Node                  ┊ Port ┊ Usage  ┊ Conns ┊      State ┊ CreatedOn           ┊
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ pvc-db6eb0df-29fe-41e0-8b1c-94ec032b3343 ┊ centos-7-k8s-100.test ┊ 7001 ┊ Unused ┊ Ok    ┊   UpToDate ┊ 2021-05-27 10:00:39 ┊
┊ pvc-db6eb0df-29fe-41e0-8b1c-94ec032b3343 ┊ centos-7-k8s-101.test ┊ 7001 ┊ Unused ┊ Ok    ┊   UpToDate ┊ 2021-05-27 10:00:40 ┊
┊ pvc-db6eb0df-29fe-41e0-8b1c-94ec032b3343 ┊ centos-7-k8s-102.test ┊ 7001 ┊ Unused ┊ Ok    ┊ TieBreaker ┊ 2021-05-27 10:00:29 ┊
┊ pvc-db67eab4-dbf6-4560-8270-141d0214d70e ┊ centos-7-k8s-100.test ┊ 7000 ┊ Unused ┊ Ok    ┊   UpToDate ┊ 2021-05-27 10:00:34 ┊
┊ pvc-db67eab4-dbf6-4560-8270-141d0214d70e ┊ centos-7-k8s-101.test ┊ 7000 ┊ Unused ┊ Ok    ┊   UpToDate ┊ 2021-05-27 10:00:34 ┊
┊ pvc-db67eab4-dbf6-4560-8270-141d0214d70e ┊ centos-7-k8s-102.test ┊ 7000 ┊ Unused ┊ Ok    ┊ TieBreaker ┊ 2021-05-27 10:00:29 ┊
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
root@vm:~/csi-snap-test# kubectl linstor sp l
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool          ┊ Node                  ┊ Driver   ┊ PoolName                          ┊ FreeCapacity ┊ TotalCapacity ┊ CanSnapshots ┊ State ┊ SharedName ┊
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltDisklessStorPool ┊ centos-7-k8s-100.test ┊ DISKLESS ┊                                   ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ centos-7-k8s-101.test ┊ DISKLESS ┊                                   ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ centos-7-k8s-102.test ┊ DISKLESS ┊                                   ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ autopool-sda         ┊ centos-7-k8s-100.test ┊ LVM_THIN ┊ linstor_autopool-sda/autopool-sda ┊     1.99 GiB ┊      1.99 GiB ┊ True         ┊ Ok    ┊            ┊
┊ autopool-sda         ┊ centos-7-k8s-101.test ┊ LVM_THIN ┊ linstor_autopool-sda/autopool-sda ┊     1.99 GiB ┊      1.99 GiB ┊ True         ┊ Ok    ┊            ┊
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

Works for me :shrug: I'm using these storage classes
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-xfs
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
parameters:
  autoPlace: "2"
  storagePool: "autopool-sda"
  csi.storage.k8s.io/fstype: xfs
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-ext4
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
parameters:
  autoPlace: "2"
  storagePool: "autopool-sda"
  csi.storage.k8s.io/fstype: ext4
```

**Comment by Omar007** [comment]
And you did nothing extra beyond adding the additional satellite set?  
Or does it by default only work/participate on new resources/volumes and not on existing ones maybe?

Piraeus operator is deployed with values:
```
operator:
  controller:
    luksSecret: piraeus
  satelliteSet:
    kernelModuleInjectionImage: docker.io/omar007/piraeus-drbd-archlinux:latest
    imagePullPolicy: Always
    storagePools:
      lvmPools:
        - name: lvm-thick-ssd
          volumeGroup: piraeus-thickssd
          # Only `jbod` supported at the moment
          raidLevel: jbod
          devicePaths:
            - /dev/sda
            - /dev/sdb
        - name: lvm-thick-nvme
          volumeGroup: piraeus-thicknvme
          devicePaths:
            - /dev/nvme0n1

csi:
  enableTopology: true

csi-snapshotter:
  enabled: false

haController:
  enabled: false

stork:
  enabled: false
```

Storage classes:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linstor-csi-thickssd-kubevirt
provisioner: linstor.csi.linbit.com
parameters:
  resourceGroup: "kubevirt-thickssd"
  placementCount: "2"
  storagePool: "lvm-thick-ssd"
  encryption: "true"
  DrbdOptions/Net/allow-two-primaries: "yes"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linstor-csi-thicknvme-kubevirt
provisioner: linstor.csi.linbit.com
parameters:
  resourceGroup: "kubevirt-thicknvme"
  placementCount: "2"
  storagePool: "lvm-thick-nvme"
  encryption: "true"
  DrbdOptions/Net/allow-two-primaries: "yes"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linstor-csi-thickssd
provisioner: linstor.csi.linbit.com
parameters:
  resourceGroup: "standard-thickssd"
  placementCount: "2"
  storagePool: "lvm-thick-ssd"
  encryption: "true"
  mountOpts: "noatime"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: linstor-csi-thicknvme
provisioner: linstor.csi.linbit.com
parameters:
  resourceGroup: "standard-thicknvme"
  placementCount: "2"
  storagePool: "lvm-thick-nvme"
  encryption: "true"
  mountOpts: "noatime"
allowVolumeExpansion: true
```

The additional satellite set (arbitrator):
```
kind: LinstorSatelliteSet
apiVersion: piraeus.linbit.com/v1
metadata:
  name: piraeus-arbitrator
  namespace: storage-operators
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
  controllerEndpoint: http://piraeus-cs.storage-operators.svc:3370
  kernelModuleInjectionImage: docker.io/omar007/piraeus-drbd-archlinux:latest
  kernelModuleInjectionMode: Compile
  satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.12.3
  imagePullPolicy: Always
  drbdRepoCred: ""
  priorityClassName: ""
```

Piraeus cs controller output/data:
```
LINSTOR ==> n l
╭───────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node                                   ┊ NodeType   ┊ Addresses                  ┊ State  ┊
╞═══════════════════════════════════════════════════════════════════════════════════════════╡
┊ avalon                                 ┊ SATELLITE  ┊ 10.50.255.252:3366 (PLAIN) ┊ Online ┊
┊ ida                                    ┊ SATELLITE  ┊ 10.50.255.251:3366 (PLAIN) ┊ Online ┊
┊ othala                                 ┊ SATELLITE  ┊ 10.50.255.250:3366 (PLAIN) ┊ Online ┊
┊ piraeus-cs-controller-7869bff956-js2gd ┊ CONTROLLER ┊ 10.50.0.67:3366 (PLAIN)    ┊ Online ┊
╰───────────────────────────────────────────────────────────────────────────────────────────╯

LINSTOR ==> sp l
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ StoragePool          ┊ Node   ┊ Driver   ┊ PoolName          ┊ FreeCapacity ┊ TotalCapacity ┊ CanSnapshots ┊ State ┊ SharedName ┊
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ DfltDisklessStorPool ┊ avalon ┊ DISKLESS ┊                   ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ ida    ┊ DISKLESS ┊                   ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ DfltDisklessStorPool ┊ othala ┊ DISKLESS ┊                   ┊              ┊               ┊ False        ┊ Ok    ┊            ┊
┊ lvm-thick-nvme       ┊ ida    ┊ LVM      ┊ piraeus-thicknvme ┊    18.14 GiB ┊     93.16 GiB ┊ False        ┊ Ok    ┊            ┊
┊ lvm-thick-nvme       ┊ othala ┊ LVM      ┊ piraeus-thicknvme ┊    18.14 GiB ┊     93.16 GiB ┊ False        ┊ Ok    ┊            ┊
┊ lvm-thick-ssd        ┊ ida    ┊ LVM      ┊ piraeus-thickssd  ┊   796.58 GiB ┊      1.82 TiB ┊ False        ┊ Ok    ┊            ┊
┊ lvm-thick-ssd        ┊ othala ┊ LVM      ┊ piraeus-thickssd  ┊   796.58 GiB ┊      1.82 TiB ┊ False        ┊ Ok    ┊            ┊
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

LINSTOR ==> rg l
╭─────────────────────────────────────────────────────────────────────────────╮
┊ ResourceGroup      ┊ SelectFilter                    ┊ VlmNrs ┊ Description ┊
╞═════════════════════════════════════════════════════════════════════════════╡
┊ DfltRscGrp         ┊ PlaceCount: 2                   ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ kubevirt-thicknvme ┊ PlaceCount: 2                   ┊ 0      ┊             ┊
┊                    ┊ StoragePool(s): lvm-thick-nvme  ┊        ┊             ┊
┊                    ┊ LayerStack: ['DRBD', 'STORAGE'] ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ kubevirt-thickssd  ┊ PlaceCount: 2                   ┊ 0      ┊             ┊
┊                    ┊ StoragePool(s): lvm-thick-ssd   ┊        ┊             ┊
┊                    ┊ LayerStack: ['DRBD', 'STORAGE'] ┊        ┊             ┊
╞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄╡
┊ standard-thickssd  ┊ PlaceCount: 2                   ┊ 0      ┊             ┊
┊                    ┊ StoragePool(s): lvm-thick-ssd   ┊        ┊             ┊
┊                    ┊ LayerStack: ['DRBD', 'STORAGE'] ┊        ┊             ┊
╰─────────────────────────────────────────────────────────────────────────────╯

LINSTOR ==> r l -a
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName                             ┊ Node   ┊ Port ┊ Usage  ┊ Conns ┊    State ┊ CreatedOn           ┊
╞════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ pvc-1caf047b-2b79-40f1-bcd3-734b32ad7f55 ┊ ida    ┊ 7008 ┊ InUse  ┊ Ok    ┊ UpToDate ┊ 2021-02-05 20:15:53 ┊
┊ pvc-1caf047b-2b79-40f1-bcd3-734b32ad7f55 ┊ othala ┊ 7008 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2021-02-05 20:15:53 ┊
┊ pvc-6a831f17-ee61-4516-92c6-b29d58f9764d ┊ ida    ┊ 7014 ┊ InUse  ┊ Ok    ┊ UpToDate ┊ 2021-02-15 11:58:39 ┊
┊ pvc-6a831f17-ee61-4516-92c6-b29d58f9764d ┊ othala ┊ 7014 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2021-02-15 11:58:39 ┊
...
┊ pvc-e8070a9f-fb25-41ad-acc6-f4965aaa408c ┊ ida    ┊ 7012 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2021-02-05 20:33:32 ┊
┊ pvc-e8070a9f-fb25-41ad-acc6-f4965aaa408c ┊ othala ┊ 7012 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2021-02-05 20:33:32 ┊
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
