### ISSUE TITLE
Snapshotting not working - Storage driver doesn't support snapshots

### ISSUE THREAD

**Issue by boomanaiden154** [piraeusdatastore/piraeus-operator#186]
I have been trying to get snapshotting to work on some of my PVCs that are managed by the Piraeus chart and I am not able to get it working. After I added in the necessary CRDs and created a volume snapshot class and a volume snapshot of one of my PVCs, Piraeus fails to create the volume snapshot. The following error is repeated many times in the logs for the linstor controller:
```
22:24:10.794 [grizzly-http-server-0] ERROR LINSTOR/Controller - SYSTEM - Storage driver 'LVM' does not support snapshots. [Report number 60B32B9B-00000-000936]
```
I have verified that creating snapshots on the host system within the LVM pool does actually work, but for some reason the linstor controller as deployed in Piraeus doesn't see it this way. The systems in question are running Ubuntu 20.04.
Snapshot class:
``` yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: testing-snapshot-class
driver: linstor.csi.linbit.com
deletionPolicy: Delete
```
Volume Snapshot:
``` yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-test
spec:
  volumeSnapshotClassName: testing-snapshot-class
  source:
    persistentVolumeClaimName: db-pvc
```
LVM config for piraeus chart:
``` yaml
operator:
  satelliteSet:
    storagePools:
      lvmPools:
        - name: hdd
          volumeGroup: hdd
        - name: ssd
          volumeGroup: ssd
```
The expected behavior would be for the volume snapshot to be created, but there seems to a bug/configuration issue in regards to interfacing with the host LVM volumes.
