### ISSUE TITLE
Ussage unclear / not working?

### ISSUE THREAD

**Issue by catsem** [piraeusdatastore/piraeus-operator#201]
Hello,

I found your project on my search for persistant native storage for our on-prem kubernetes cluster (under construction) and I liked the approach and also the numbers (benchmarks, etc.) looks very promising. 

So wanted to try it out on a fresh 3 node microk8s cluster (Ubuntu 20.04 based).

Bootstraping the cluster with hostPath etcd and your piraeus-operator helm charts all looked good and worked quite seamless.

Then the question: How can I use it in a pod. Well there is nothing on the piraeus side, so I tried what I found in the linstor documentation.
But wait, it seems like it does (silently) not work, because my volumes does not get any data...

-> Details:

Steps performed:
- Install 3 microk8s Ubuntu 20.04 nodes in a cluster
- Setup hostpath etcd on the 3 nodes
- helm install piraeus operator
- Create LVM thinPool on each of the 3 nodes: lvcreate -L 10G -T vg00/linstor-thinpool
- kubectl apply the following yaml:
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor
provisioner: linstor.csi.linbit.com
parameters:
  autoPlace: "3"
  storagePool: "thinpool"
  csi.storage.k8s.io/fstype: xfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ubuntu-linstor
spec:
  storageClassName: linstor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: ubuntu:bionic
    command: [/bin/bash]
    args: ["-c", "while true; do sleep 10; done"]
    volumeMounts:
    - name: ubuntu
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: ubuntu
    persistentVolumeClaim:
      claimName: "ubuntu-linstor"
```

Then I saw that a `pvc-<id>` thin-volume is created on each of my 3 nodes. Looked good so far.

Afterwards I just opened a bash in my ubuntu container and tried to write something to /data with **dd if=/dev/urandom of=/data/test.img bs=1M count=2000**. 
When I exec lvs on my nodes now, I see no data on the volumes: 
```bash
  LV                                             VG   Attr       LSize   Pool             Origin Data%  Meta%  Move Log Cpy%Sync Convert
  linstor-thinpool                               vg00 twi-aotz--  10,00g                         0,12   10,68
  pvc-cb88951c-f2a4-4b40-ba17-59c5c7c10e13_00000 vg00 Vwi-aotz--   5,00g linstor-thinpool        0,23
```

I also mounted the /dev/drbd1000 directly on the nodes and my test.img was not there. Where is my mistake?

I had no error messages at all!

Thanks for reading all this and telling me your ideas :)
