### ISSUE TITLE
Question about Helm install

### ISSUE THREAD

**Issue by Evantage-WS** [piraeusdatastore/piraeus-operator#223]
Hi there,

Small question, I do see that automaticStorageType is depricated. Do you have an example for helm with the option on the command line how to use the storagepools and volumes ?

Thanks!

**Comment by WanzenBug** [comment]
Take a look at: https://github.com/piraeusdatastore/piraeus-operator/blob/master/doc/storage.md

I don't think you can add these "complex" objects via the command line directly, so you have to use the yaml file + `-f` option

**Comment by ws-prive** [comment]
Ok, thanks. I am using this now, can you please confirm or give some advice how to set it up properly? I do have stork disabled and 3 replicas, this is for testing later. Ofcourse I can move all the commandline options to the yaml file as well, but that's also for later.

```
helm upgrade --install piraeus ./charts/piraeus -f storagepool.yaml \
  --namespace piraeus \
  --create-namespace \
  --set csi.controllerReplicas=3 \
  --set etcd.replicas=3 \
  --set operator.replicas=3 \
  --set operator.controller.replicas=3 \
  --set stork.enabled=false \
  --set stork.replicas=3 \
  --set operator.satelliteSet.kernelModuleInjectionImage=quay.io/piraeusdatastore/drbd9-focal
```
the file storagepool.yaml contains (sdc is my empty disk):

```
operator:
  satelliteSet:
    storagePools:
      lvmThinPools:
      - name: lvm-thin
        thinVolume: thinpool
        volumeGroup: linstor_thinpool
        devicePaths:
        - /dev/sbc
```

Thanks!

**Comment by WanzenBug** [comment]
You have a typo in `/dev/sbc` should be `/dev/sdc`.

**Comment by ws-prive** [comment]
Thanks, however, I do not have a clue what's wrong, I think I forgot one step:

```
+----------------------------------------------------------------------------------------------------------------------------------------------+
| StoragePool          | Node        | Driver   | PoolName                  | FreeCapacity | TotalCapacity | CanSnapshots | State | SharedName |
|==============================================================================================================================================|
| DfltDisklessStorPool | k8s-worker1 | DISKLESS |                           |              |               | False        | Ok    |            |
| DfltDisklessStorPool | k8s-worker2 | DISKLESS |                           |              |               | False        | Ok    |            |
| DfltDisklessStorPool | k8s-worker3 | DISKLESS |                           |              |               | False        | Ok    |            |
| lvm-thin             | k8s-worker1 | LVM_THIN | linstor_thinpool/thinpool |        0 KiB |         0 KiB | True         | Error |            |
| lvm-thin             | k8s-worker2 | LVM_THIN | linstor_thinpool/thinpool |        0 KiB |         0 KiB | True         | Error |            |
| lvm-thin             | k8s-worker3 | LVM_THIN | linstor_thinpool/thinpool |        0 KiB |         0 KiB | True         | Error |            |
+----------------------------------------------------------------------------------------------------------------------------------------------+
ERROR:
Description:
    Node: 'k8s-worker1', storage pool: 'lvm-thin' - Failed to query free space from storage pool
Cause:
    Volume group 'linstor_thinpool' not found
ERROR:
Description:
    Node: 'k8s-worker2', storage pool: 'lvm-thin' - Failed to query free space from storage pool
Cause:
    Volume group 'linstor_thinpool' not found
ERROR:
Description:
    Node: 'k8s-worker3', storage pool: 'lvm-thin' - Failed to query free space from storage pool
Cause:
    Volume group 'linstor_thinpool' not found
❯ kubectl exec deployment/piraeus-cs-controller -n piraeus -- linstor physical-storage list
+--------------------------------------------------+
| Size        | Rotational | Nodes                 |
|==================================================|
| 26843545600 | True       | k8s-worker3[/dev/sdc] |
|             |            | k8s-worker1[/dev/sdc] |
|             |            | k8s-worker2[/dev/sdc] |
+--------------------------------------------------+
```
Can you help me?

**Comment by ws-prive** [comment]
I have also tested it without a name at volumeGroup and with "" as name os the volumeGroup, but then piraeus won't start:

```
operator:
  satelliteSet:
    storagePools:
      lvmThinPools:
      - name: lvm-thin
        thinVolume: thinpool
        volumeGroup: ""
        devicePaths:
        - /dev/sdc
```
```
operator:
  satelliteSet:
    storagePools:
      lvmThinPools:
      - name: lvm-thin
        thinVolume: thinpool
        volumeGroup:
        devicePaths:
        - /dev/sdc
```
