### ISSUE TITLE
node affinity for drbd / storage pool

### ISSUE THREAD

**Issue by todeb** [piraeusdatastore/piraeus-operator#236]
Hello,

by default when I create a storagepool eg.:
```
operator:
  satelliteSet:
    storagePools:
      lvmThinPools:
      - name: lvm-thin
        thinVolume: thinpool
        volumeGroup: linstor_thinpool
        devicePaths:
        - /dev/sdc
```
it is trying to create that pool on all of the worker nodes.

I would like to have only 3 dedicated nodes with specific label running drbd or storage pools. Workers without this label should not be provisioned for storage. Is it possible?
