### ISSUE TITLE
Storage pool only available on some nodes

### ISSUE THREAD

**Issue by phoenix-bjoern** [piraeusdatastore/piraeus-operator#267]
When storage pools are only available on certain nodes in the cluster the SatelliteSet definition in the deployment will try to create the storage pool on each node even if the pool actually does not exist.

Example:
```
satelliteSet:
    enabled: true
    satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.17.0
    storagePools:
      lvmThinPools:
      - name: lvm-thin
        volumeGroup: vg-pool
        thinVolume: disk-redundant
      - name: lvm-thin-nfs-pool
        volumeGroup: vg-nfs-pool
        thinVolume: nfs-pool
      - name: lvm-thin-px-internal
        volumeGroup: vg-pool-px-internal
        thinVolume: disk-redundant-px-internal
```

The `linstor sp l` shows an error state on the nodes where the LVM pool doesn't exist:

![Bildschirmfoto 2022-02-02 um 16 53 07](https://user-images.githubusercontent.com/846569/152188850-684b2767-cffd-4e03-a0a9-3d9a19805007.png)

While this is only a minor issue and the error message `Volume group 'vg-nfs-pool' not found` could be ignored, IMHO there should either an option in the CRD to specify the nodes (optional) where a pool is available or the controller should check the availability of the pool on the node before creating it in Linstor (at least that was the case before 1.7.0) to avoid such a misconfiguration during deployment. Otherwise you'll have to clean it up manually (`linstor sp delete <node> <pool>`) after each deployment (and I'm actually not sure whether the controller will configure the storage pools again if it gets restarted).
