### ISSUE TITLE
Wrong label selector in piraeus-operator-metrics service

### ISSUE THREAD

**Issue by redtex** [piraeusdatastore/piraeus-operator#301]
Hi !!!

The piraeus-operator-metrics  service has following label selector:

```
apiVersion: v1                                                                                                                                                                                                     
kind: Service                                                                                                                                                                                                      
metadata:                                                                                                                                                                                                          
  labels:                                                                                                                                                                                                          
    name: piraeus-operator                                                                                                                                                                                         
  name: piraeus-operator-metrics                                                                                                                                                                                   
  namespace: linstor                                                                                                                                                                                               
spec:                                                                                                                                                                                                              
  .....
  selector:                                                                                                                                                                                                        
    name: piraeus-operator                                                                                                                                                                                         
```

but corresponding Deployment has different labels:

```
apiVersion: apps/v1                                                                                                                                                                                                
kind: Deployment                                                                                                                                                                                                   
metadata:                                                                                                                                                                                                          
  labels:                                                                                                                                                                                                          
    name: piraeus-op-operator                                                                                                                                                                                      
  name: piraeus-op-operator                                                                                                                                                                                        
  namespace: linstor                                                                                                                                                                                               
spec:                                                                                                                                                                                                              
  selector:                                                                                                                                                                                                        
    matchLabels:                                                                                                                                                                                                   
      name: piraeus-op-operator    
  template:                                                                                                                                                                                                        
    metadata:                                                                                                                                                                                                      
      labels:                                                                                                                                                                                                      
        name: piraeus-op-operator                                                                                                                                                                                  
.......
```
which leads to absence endpoints in Service.
