### ISSUE TITLE
CSI Node and Controller should define containerPort 9808

### ISSUE THREAD

**Issue by bc185174** [piraeusdatastore/piraeus-operator#304]
Hi,

The container `linstor-csi-plugin` deployed by both the csi-controller and csi-node's do not define the containerPort 9808 (TCP). This change is need for the piraeus deployments to work with [linkerd](https://linkerd.io/).

Suggested changes would be add the following field to the `linstor-csi-plugin` container:

```yaml
ports:
    - containerPort: 9808
      name: healthz
      protocol: TCP
```

I assume the csi deployment/daemon-sets are create by the operator? Would be happy to make the necessary changes.
