### ISSUE TITLE
Local spath-as-a-service in a cluster

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/piraeus-operator#315]
Hi @WanzenBug,

We're faced with the [problem](https://github.com/deckhouse/deckhouse/pull/1726) of using kernel-module-injector in closed enviroments (enviroments without public internet connectivity)
So we decided to run [spatch-as-a-service](https://github.com/LINBIT/saas) locally in same namespace for our platform.

I prepared patch for DRBD https://github.com/LINBIT/drbd/pull/41 (I didn't sent it to drbd-dev mailing list yet)

The patch allows to set SPAAS_URL enviroment variable to communicate to while building drbd kernel module.
Currently we specify this URL as [constant in our Dockerfile](https://github.com/deckhouse/deckhouse/pull/1761/files#diff-f60eee31d9285ede714e7d1560ef62e14665a7294b66f9ae67cda67e560d1485), but it does not allow to mount actual CA to the pod and specify CA file.

I'm thinking about modify operator to provide `extraVolumeMounts` functionality, eg:

```yaml
operator:
  satelliteSet:
    additionalEnv:
    - name: SPAAS_URL
       value: "--cacert /etc/spaas/certs/ca.crt https://spaas:2020"
    kernelModuleInjectionExtraVolumeMounts:
    - mountPath: /etc/spaas/certs/ca.crt
      name: spaas-certs
      readOnly: true
      subPath: ca.crt
    extraVolumes:
    - name: spaas-certs
      secret:
        secretName: spaas-certs
```

or adding two new variables like:

```yaml
operator:
  satelliteSet:
    spaasURL: "--cacert /etc/spaas/certs/ca.tls https://spaas:2020"
    spaasSecret: "spaas-certs"
```

which option do you prefer or maybe do you have better idea?
