### ISSUE TITLE
Can't remove nodeAffinity

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/piraeus-operator#321]
When unsetting `nodeAffinity` the deployment is not going to updated.

I tried both ways:

```yaml
affinity: {}
```

and

```yaml
affinity:
  nodeAffinity: {}
  podAntiAffinity: {}
```

checked with linstorcontroller, linstorsatelliteset and linstorcsiplugin resources
