### ISSUE TITLE
Operator can't patch the servicemonitor

### ISSUE THREAD

**Issue by kashapovd** [piraeusdatastore/piraeus-operator#329]
Hi. I've tried to redeploy piraeus-operator helm chart. After some redeployments (delete helm chart and chart namespace) operator can't patch the servicemonitor:
```
failed to reconcile monitoring resources: failed to reconcile servicemonitor
    definition: failed to apply patch: the body of the request was in an unknown format
    - accepted media types include: application/json-patch+json, application/merge-patch+json,
    application/apply-patch+yaml
```
If I disable monitoring feature, operator works just fine.
My configuration:
```
etcd:
  enabled: false
csi:
  controllerReplicas: 3
operator:
  controller:
    dbConnectionURL: "jdbc:postgresql://postgresql-ha-pgpool/linstor?user=linstor&password=somepassword"
  args:
    createMonitoring: true
  satelliteSet:
    kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-focal
    storagePools:
      lvmPools:
        - name: linstor-pool
          volumeGroup: some-lvm-volume-group
haController:
  enabled: true
  replicas: 3
```
P.S:
ServiceMonitor resource of piraeus cs constantly recreated in a loop:
```
1.6615208076920202e+09  ERROR   controller.LinstorController-controller Reconciler error        {"name": "piraeus-cs", "namespace": "linstor", "error": "multiple errors: failed to reconcile servicemonitor definition: recreate failed: could not create new resource: object is being deleted: servicemonitors.monitoring.coreos.com \"piraeus-cs\" already exists"}
time="2022-08-26T13:33:27Z" level=warning msg="failed to update status. original error: failed to add finalizer: Operation cannot be fulfilled on linstorcontrollers.piraeus.linbit.com \"piraeus-cs\": the object has been modified; please apply your changes to the latest version and try again" controller=LinstorController resquestName=piraeus-cs resquestNamespace=linstor
1.6615208077090335e+09  ERROR   controller.LinstorController-controller Reconciler error        {"name": "piraeus-cs", "namespace": "linstor", "error": "Operation cannot be fulfilled on linstorcontrollers.piraeus.linbit.com \"piraeus-cs\": the object has been modified; please apply your changes to the latest version and try again"}
time="2022-08-26T13:33:27Z" level=warning msg="failed to update status. original error: failed to add finalizer: Operation cannot be fulfilled on linstorcontrollers.piraeus.linbit.com \"piraeus-cs\": the object has been modified; please apply your changes to the latest version and try again" controller=LinstorController resquestName=piraeus-cs resquestNamespace=linstor
1.6615208078944387e+09  ERROR   controller.LinstorController-controller Reconciler error        {"name": "piraeus-cs", "namespace": "linstor", "error": "Operation cannot be fulfilled on linstorcontrollers.piraeus.linbit.com \"piraeus-cs\": the object has been modified; please apply your changes to the latest version and try again"}
time="2022-08-26T13:33:28Z" level=info msg="controller Reconcile: reconcile loop end" controller=LinstorController err="multiple errors: failed to reconcile servicemonitor definition: recreate failed: could not create new resource: object is being deleted: servicemonitors.monitoring.coreos.com \"piraeus-cs\" already exists" resquestName=piraeus-cs resquestNamespace=linstor result="{false 0s}"
```
Please, help ;)
