### ISSUE TITLE
[v2] Configure the image pull secrets, pull policy and image tag

### ISSUE THREAD

**Issue by WanzenBug** [piraeusdatastore/piraeus-operator#343]
Along with the registry, could we configure the image pull secrets, pull policy and image tag? Makes it simpler for end-users to automate upgrading the application. For instance, using `yq` to adjust the image tag in a Makefile. More than happy to help contribute as always.

```yaml
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec:
  imageSource: 
    repository: registry.example.com/piraeus
    tag: v1.10.0
    pullPolicy: IfNotPresent
    pullSecrets:
    - "SecretName"
```

_Originally posted by @bc185174 in https://github.com/piraeusdatastore/piraeus-operator/issues/334#issuecomment-1288804432_

**Comment by WanzenBug** [comment]
Currently, image controlled by piraeus are configured here: https://github.com/piraeusdatastore/piraeus-operator/blob/v2/pkg/imageversions/defaults.yaml

That file is backed into the binary using `go:embed`. Instead we could:
* expose it as a config map
* expand the syntax a bit to include pull policy
* find a way to include pull secrets?
* extend it to the various sidecar containers from `registry.k8s.io`

**Comment by WanzenBug** [comment]
One issue I see with using a config map: Often you only want to change one aspect (for example: the registry). With "normal" kustomize resources this would be easy, as kustomize would merge the original with a patched version. But I don't think this approach would work, as for kustomize the config map would just be a single string, that can't be patched

**Comment by bc185174** [comment]
I think the LinstorCluster CR would be ideal. Assuming the operator creates/patches the deployment/daemonsets with the new configurations? And just default when the fields are omitted.

The operator itself is the only exception as the version/images etc are configured via kustomize.

**Comment by WanzenBug** [comment]
Another thing I was thinking about, adding the equivalent of the `images` section from a kustomization file. Since we already use kustomize to deploy, and also allow users to write kustomize patches, it would be pretty consistent. We would need to extend it a bit to also let the user select pull secrets and pull policy. So we could have:
```
spec:
  images:
    - name: linstor-controller
      newName: private.example.com/piraeus
      newTag: v1.20.1
```

Adding pullPolicy just for certain images could be complicated however
