### ISSUE TITLE
`controllerEndpoint` issue, only first endpoint is used

### ISSUE THREAD

**Issue by jonathon2nd** [piraeusdatastore/piraeus-operator#393]
We have the piraeus-operator installed on k8s, with linstor cluster on host.
Deployed with helm.
REPO URL: https://github.com/piraeusdatastore/piraeus-operator.git
TARGET REVISION: v1.10.1

Values
```
---
operator:
  controller:
    enabled: false
  satelliteSet:
    kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-centos8:v9.2.1
    satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.20.0-1
etcd: 
  enabled: false
controllerEndpoint: http://10.2.4.10:3370/,http://10.2.4.12:3370/,http://10.2.4.11:3370/
```

So you can see we have `controllerEndpoint: http://10.2.4.10:3370/,http://10.2.4.12:3370/,http://10.2.4.11:3370/`, the problem is it only works if the first host in the list is the controller. When we did upgrades on the cluster and the controller failed over to another host, the  operator failed, as it no longer had connection. It did not try the other two hosts in the list.

I don't have error logs now, as this happened a little bit again, and the errors were very basic and I did not record.
