### ISSUE TITLE
drbd-reactor crashing

### ISSUE THREAD

**Issue by nashant** [piraeusdatastore/piraeus-operator#415]
One of my satellite pods is crashlooping. It's because of the `drbd-reactor` pod which is giving only the following logs:
```
$ k logs -n piraeus-datastore server -c drbd-reactor
Error: main: core did not exit successfully

Caused by:
    sending on a disconnected channel
```
Any idea?

**Comment by WanzenBug** [comment]
Which version of the image is running? If your are not already using the `v1.0.0` image, please try to upgrade to that, as that has generally better error reporting.

**Comment by nashant** [comment]
Yup, already using `v1.0.0`

**Comment by nashant** [comment]
Any thoughts? Can I increase logging somehow?

**Comment by WanzenBug** [comment]
You might be able to add a second entry to the `piraeus-op-node-monitoring` configmap:

```
data:
  log.toml:  |
    [[log]]
    level = "debug"
```

**Comment by RichardSufliarsky** [comment]
Experiencing the same and even with the trace level, there is no more info:
![image](https://user-images.githubusercontent.com/31887324/232444376-fb836373-ada1-4d5d-8a6a-339b6b100847.png)

**Comment by WanzenBug** [comment]
We noticed that sometimes reactor still discards some log messages, especially the log message when creating the Prometheus socket. I assume in both cases this is related to reactor for some reason not being able to bind to `[::]:9942`. As for why, I cannot tell. Perhaps some strange network configuration with disabling IPv6 on the kernel level?

**Comment by WanzenBug** [comment]
Then you probably need to patch the reactor config to use `0.0.0.0:9942` instead of the anylocal `[::]` address. This normally works fine even on IPv4 only systems, but directly disabling the IPv6 subsystem tends to break those.

**Comment by RichardSufliarsky** [comment]
Please, can you point me where can I change this globally via CRD? When I edit _nodename-reactor-config_ config map directly and delete the pod for that _nodename_ to restart drbd-reactor, then the address in config map gets replaced back to `[::]`, though log.tml part with trace stays there untouched (I added that also manually).

**Comment by RichardSufliarsky** [comment]
Sorry, found it: https://github.com/piraeusdatastore/piraeus-operator/issues/441#issuecomment-1484970615

**Comment by RichardSufliarsky** [comment]
No `drbd-reactor` container crash since I have set Prometheus address to `0.0.0.0:9942`:
```
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: drbd-reactor-trace
spec:
  patches:
    - target:
        kind: ConfigMap
        name: reactor-config
      patch: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: reactor-config
          labels:
            app.kubernetes.io/component: linstor-satellite
        data:
          prometheus.toml: |
            [[prometheus]]
            enums = true
            address = "0.0.0.0:9942"
            
            [[log]]
            level = "trace"
          log.toml: |
            [[log]]
            level = "trace"
```
