### ISSUE TITLE
Docs on Setting Up Local Disk for Storage Pools in v2

### ISSUE THREAD

**Issue by inviscid** [piraeusdatastore/piraeus-operator#422]
Hi,

We were testing with v1 and had things running but it took a pretty significant effort to get to the starting line.  Very excited to jump into using v2 as it seems like it solves many of the challenges we encountered while setting up a test system.

Reading the Quick Start guide, there is a reference to a thin pool setup but it now references a directory path rather than the v1 references to LVM pools and Volume Groups.  However, I can't find any information on what these new settings relate to with regards to the LVM pool.

In the v2 tutorial example this is provided:
```
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool
spec:
  storagePools:
    - name: pool1
      fileThinPool:
        directory: /var/lib/piraeus-datastore/pool1
```

However, the v1 settings seem quite different and I'm not sure what needs to be specified in the v2 to properly reference the LVM pool.  The v1 config we had previously was:

```
storagePools:
    lvmPools: []
    lvmThinPools:
      - name: lvm-thin
        thinVolume: thinpool
        volumeGroup: vg_local_ssds
    zfsPools: []
```

For context, we are running on GKE and pooling local SSDs using a daemonset.

Would it be possible to provide a little more context around the v2 LinstorSatelliteConfiguration config so that we know how to connect the dots.

Thanks...

**Comment by inviscid** [comment]
Is the correct stanza for LVM thin pools now:
```
storagePools:
  - name: lvm-thin
     thinVolume: thinpool
     volumeGroup: vg_local_ssds
```

Thus eliminating the grouping of pool types?  Sorry for such a basic question.  I just can't find any documentation on this at the moment.
