### ISSUE TITLE
How to use operator on Talos Linux

### ISSUE THREAD

**Issue by Nosmoht** [piraeusdatastore/piraeus-operator#429]
Hi all,

i'm using Talos Linux as OS and would like to know how to use the operator on Talos.

I'm using the prebuild Kernel module that comes with Talos. Module is already loaded:
```shell
$ talosctl -n node01 read /proc/modules
drbd 643072 - - Live 0xffffffffc0010000 (O)
```

Talos also doesn't have `/usr/lib/modules`:
```shell
$ talosctl -n node01 ls /usr/lib/modules
NODE   NAME
1 error occurred:
 rpc error: code = Unknown desc = lstat /usr/lib/modules: no such file or directory
```

Could you please provide an example configuration that can be used to deploy the Operator using helm? 

I've tried to use following Helm `values.yaml` file:
```yaml
installCRDs: true
chart:
  version: v2.0.1
etcd:
  enabled: false
operator:
  controller:
    dbConnectionURL: k8s
  satelliteSet:
    kernelModuleInjectionImage: "" # None
    kernelModuleInjectionMode: DepsOnly
    storagePools:
      lvmPools:
        - name: lvm-thick
          volumeGroup: linstor_thickpool
          devicePaths:
            - /dev/vdb
  satelliteSetConfiguration:
    patches:
      - target:
          kind: Pod
          name: satellite
        patch: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: satellite
          spec:
            initContainers:
            - name: drbd-shutdown-guard
              $patch: delete
haController:
  enabled: true
```

First issue with my config is that the operator still deploys `quay.io/piraeusdatastore/drbd9-jammy:v9.2.2` which fails, for sure.
The `satelliteSetConfiguration` is needed as Talos doesn't have `Systemd`.

So at the end the operator should just use the `drbd` module already loaded. Is that somehow possible or can't i use Linstor on Talos Linux?

Kind regards

**Comment by WanzenBug** [comment]
Your patch will need to look like this:

```yaml
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: no-drbd-init
spec:
  patches:
  - target:
      kind: Pod
      name: satellite
    patch: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: satellite
      spec:
        initContainers:
          - name: drbd-shutdown-guard
            $patch: delete
          - name: drbd-module-loader
            $patch: delete
        volumes:
          - name: run-systemd-system
            $patch: delete
          - name: run-drbd-shutdown-guard
            $patch: delete
          - name: systemd-bus-socket
            $patch: delete
          - name: lib-modules
            $patch: delete
          - name: usr-src
            $patch: delete
```

This should remove all init containers and volumes that are not available on Talos.

**Comment by Nosmoht** [comment]
Hi @WanzenBug ,

thanks for the config, `drbd-reactor` container is starting now, but `linstor-satellite` fails with following message as everything under `/etc` is read-only in Talos. Not sure why `/etc/lvm/*` is needed at all as i didn't specify anything LVM related.

```shell
failed to generate spec: failed to mkdir "/etc/lvm/backup": mkdir /etc/lvm/backup: read-only file system
```

**Comment by WanzenBug** [comment]
> Not sure why /etc/lvm/* is needed at all as i didn't specify anything LVM related.

Because we did not make it optional in the Pod spec. We could make it optional, so it only get's pulled in when using a LVM storage pool :thinking: 

Anyways, just add more `$patch: delete` statements where needed.

**Comment by Nosmoht** [comment]
I've added 
```yaml
   ...
          - name: etc-lvm-backup
            $patch: delete
          - name: etc-lvm-archive
            $patch: delete
```

as these two mounts don't exists. Unfortunately after apply the `Satellites` `node01`, `node02`, `nodeXX` disappear and never come back so everything else wait for them to come online. Is this expected?

**Comment by WanzenBug** [comment]
No. You can check the status of the `LinstorSatellite` resources. You will likely see an error because you also need to remove them from the `mountVolumes:` list in the `linstor-satellite` container.

**Comment by Nosmoht** [comment]
Could you please assist me how to do that?

**Comment by WanzenBug** [comment]
The volume mounts are keyed by both name and path, so you need:
```yaml
        containers:
        - name: linstor-satellite
          volumeMounts:
          - mountPath: /etc/lvm/backup
            name: etc-lvm-backup
            $patch: delete
          - mountPath: /etc/lvm/archive
            name: etc-lvm-archive
            $patch: delete
```
