### ISSUE TITLE
hostPath type check failed: /lib/modules is not a directory

### ISSUE THREAD

**Issue by mrpk1906** [piraeusdatastore/piraeus-operator#434]
Hello,

I'm deploying a test cluster and I got an error, init container has failed

```
hostPath type check failed: /lib/modules is not a directory
```

I'm using Ubuntu 22.04, `/lib` is a symlink to `/usr/lib` and we are setting `type: Directory` in hostPath

```
  volumes:
    - name: lib-modules
      hostPath:
        path: /lib/modules
        type: Directory
```

I tried remove `type: Directory` from `pkg/resources/satellite/pod/node-pod.yaml` then build and redeploy the operator, it worked

Maybe we should remove `type: Directory`?
