### ISSUE TITLE
Quorum problem

### ISSUE THREAD

**Issue by lysyy** [piraeusdatastore/piraeus-operator#436]
Hellow again!
V2
No quorum, all connection is in state StandAlone, created in storageclass with placementCount: "3"
drbdadm status
pvc-21f4b924-91f8-49cd-b7de-757a6173b7e6 role:Secondary suspended:quorum
  disk:UpToDate quorum:no blocked:upper
  k02 connection:StandAlone
  k03 connection:StandAlone
  k04 connection:StandAlone
All pods running, all nodes tainted with drbd.linbit.com/lost-quorum:NoSchedule, removed taints appears again
DRBD 9.2.2

**Comment by WanzenBug** [comment]
Did you use the last patch from #435, which completely removes the NetworkPolicy? I think DRBD can't connect because of the `endPort` issue:
```
 patches:
    - target:
        kind: NetworkPolicy
        name: satellite
      patch: |-
        - op: remove
          path: /
```

If that's not the issue, I'd need to see the kernel logs.
