### ISSUE TITLE
optional drives - lvmpool 

### ISSUE THREAD

**Issue by boedy** [piraeusdatastore/piraeus-operator#437]
I am currently experiencing an issue related to my multi-cloud setup. Specifically, I would like to use network-attached block storage provided by the cloud provider to expand the capacity of the cluster. Unfortunately I don't have any control over where it will mount. It could be `/dev/sdb`, /dev/sdc`, /dev/vdb` etc.  Currently, all drives that are specified as hostDevice need to exist; otherwise, none of them will be added. Here as an example configuration:

```yaml
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-satellites
spec:
  storagePools:
    - name:  attached-storage
      lvmPool:
        volumeGroup: vg2
      source:
        hostDevices:
          - /dev/sdb
          - /dev/sdc
          - /dev/sdd
          - /dev/vdb
          - /dev/vdc
          - /dev/vdd 
```

As far as I can tell; This is where the pool is created by taking in all the drives as argument using [PhysicalStorageCreate]. (https://pkg.go.dev/github.com/LINBIT/golinstor/client#PhysicalStorageCreate). 
 https://github.com/piraeusdatastore/piraeus-operator/blob/6273a2fcbad6b3a284014b1c640f0588079d5196/controllers/linstorsatellite_controller.go#L428
 
Would there be a solution possible where we could list multiple hosts drives that are (in a sense) whitelisted to be added to the storage pool? If a drive is not present on a machine, it will just be ignored instead of rejecting all drives.
