### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by lysyy** [piraeusdatastore/piraeus-operator#438]
Hellow! Please help me get metics from sattelites like [https://github.com/LINBIT/linstor-server/blob/master/docs/prometheus.md](https://github.com/LINBIT/linstor-server/blob/master/docs/prometheus.md) .
I already have metrics from operator by adding 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: piraeus-access-for-prometheuses
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: d8-monitoring
```
And do you have alerting rules? It will be very good)
