### ISSUE TITLE
drbd-reactor fails with "sending on a disconnected channel"

### ISSUE THREAD

**Issue by lysyy** [piraeusdatastore/piraeus-operator#441]
Hello!
I have periodicaly satelite pods in CrashLoopBackOff , drbd-reactor fails with:
Error: main: core did not exit successfully

Caused by:
    sending on a disconnected channel

How can i try to fix this? Thanks

**Comment by WanzenBug** [comment]
Do you see any pattern? How often does it crash?

You can also use this configuration to increase the verbosity of drbd-reactor:
```
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: drbd-reactor-trace
spec:
  patches:
    - target:
        kind: ConfigMap
        name: reactor-config
      patch: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: reactor-config
          labels:
            app.kubernetes.io/component: linstor-satellite
        data:
          prometheus.toml: |
            [[prometheus]]
            enums = true
            address = "[::]:9942"
            
            [[log]]
            level = "trace"
```

You then need to restart the pods for it to take effect: `kubectl delete pod -l app.kubernetes.io/component=linstor-satellite`

**Comment by lysyy** [comment]
They crashes after start at this cluster
```
k01                                                    1/2     Error              4 (65s ago)     3m45s
k02                                                    2/2     Running            4 (65s ago)     3m36s
k03                                                    1/2     CrashLoopBackOff   4 (61s ago)     3m22s
k04                                                    0/2     Pending            0               3m5s
k05                                                    1/2     CrashLoopBackOff   4 (54s ago)     4m13s
k06                                                    1/2     Error              5 (93s ago)     4m
```

, but in my second cluster not so often:
```
k01                                                    2/2     Running   83 (154m ago)    4d22h
k02                                                    2/2     Running   136 (114m ago)   3d22h
k03                                                    2/2     Running   136 (154m ago)   4d22h
k04                                                    2/2     Running   192 (155m ago)   4d22h
k05                                                    2/2     Running   142 (154m ago)   4d22h
```


Logs now:
```
DEBUG [drbd_reactor] signal-handler: set up done
DEBUG [drbd_reactor] signal-handler: waiting for signals
DEBUG [drbd_reactor::events] events2_loop: starting process_events2 loop
DEBUG [drbd_reactor] main: configuration: Config {
    log: [
        LogConfig {
            level: Info,
            file: None,
        },
        LogConfig {
            level: Trace,
            file: None,
        },
    ],
    statistics_poll_interval: 60,
    snippets: Some(
        "/etc/drbd-reactor.d",
    ),
    plugins: PluginConfig {
        promoter: [],
        debugger: [],
        umh: [],
        prometheus: [
            PrometheusConfig {
                address: "[::]:9942",
                enums: true,
                id: None,
            },
        ],
    },
}
DEBUG [drbd_reactor] main: started.len()=1
TRACE [drbd_reactor::plugin::prometheus] run: start
Error: main: core did not exit successfully

Caused by:
    sending on a disconnected channel
DEBUG [drbd_reactor::events] events2_loop: send error on chanel, bye
ERROR [drbd_reactor] main: events2 processing failed: sending on a disconnected channel
```
nodes has taint "drbd.linbit.com/lost-quorum:NoSchedule", pods are in pending state until untaint nodes.

drsb-reactor 1.1.0 released, maybe try it?

**Comment by WanzenBug** [comment]
> nodes has taint "drbd.linbit.com/lost-quorum:NoSchedule", pods are in pending state until untaint nodes.

This is because the satellites are crashing. But the satellites Pods should have the right toleration to enable them to start. 

I guess something in the prometheus exporter goes wrong. For some reason the logs are not showing us why, which needs to be investigated further.

**Comment by WanzenBug** [comment]
> nodes has taint "drbd.linbit.com/lost-quorum:NoSchedule", pods are in pending state until untaint nodes.

This is because the satellites are crashing. But the satellites Pods should have the right toleration to enable them to start. 

I guess something in the prometheus exporter goes wrong. For some reason the logs are not showing us why, which needs to be investigated further.

**Comment by lysyy** [comment]
Is drbd-reactor prometheus-exporter only or it has more important role? How can we temporary disable it by patch? Or switch to latest release?

**Comment by WanzenBug** [comment]
It's prometheus exporter only. But if it's unused I'm not sure how it could possibly crash.

**Comment by lysyy** [comment]
My drbd-reactors was never scraped by prometheus,i think it receives some info (config statistics-poll-interval = 300) from drbd and stores in memory. 
I had removed drbd-reactor from sattelite
```
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: no-reactor
spec:
  patches:
    - target:
        kind: Pod
        name: satellite
      patch: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: satellite
        spec:
          containers:
          - name: drbd-reactor
            $patch: delete
```
Pods running with 1 container, kubectl -n piraeus-datastore exec deploy/linstor-controller -- linstor resource list-volumes 
shows all resources green and ok, but nodes always tainted by drbd.linbit.com/lost-quorum:NoSchedule .
