### ISSUE TITLE
"PVC is not bound" - when volumeBindingMode=WaitForFirstConsumer, "mount failed: exit status 32" - when volumeBindingMode=Immediate

### ISSUE THREAD

**Issue by RichardSufliarsky** [piraeusdatastore/piraeus-operator#442]
Trying to follow replicated volume tutorial and getting errors when starting deployment that is using defined PVC.

If I use volumeBindingMode=WaitForFirstConsumer, then the error is:
```
Unable to attach or mount volumes: unmounted volumes=[replicated-volume], unattached volumes=[replicated-volume kube-api-access-dtfsc]: error processing PVC default/replicated-volume: PVC is not bound
```

If I use volumeBindingMode=Immediate, then the error is:
```
MountVolume.SetUp failed for volume "pvc-7595e48b-6367-4305-bb71-0725945643d8" : rpc error: code = Internal desc = NodePublishVolume failed for pvc-7595e48b-6367-4305-bb71-0725945643d8: mount failed: exit status 32 Mounting command: mount Mounting arguments: -t xfs -o _netdev,nouuid /dev/drbd1005 /var/lib/kubelet/pods/c90c9e01-e912-4cb1-aef0-767c99581194/volumes/kubernetes.io~csi/pvc-7595e48b-6367-4305-bb71-0725945643d8/mount Output: mount: /var/lib/kubelet/pods/c90c9e01-e912-4cb1-aef0-767c99581194/volumes/kubernetes.io~csi/pvc-7595e48b-6367-4305-bb71-0725945643d8/mount: wrong fs type, bad option, bad superblock on /dev/drbd1005, missing codepage or helper program, or other error.
```

Environment:
 - mixed RHEL 8.7 (k8s1, k8s2, k8s3 - with disks) and 9.1 (node001, node002, node003 - diskless) nodes
 - Kubernetes 1.24.2
 - Piraeus Operator v2: quay.io/piraeusdatastore/piraeus-operator@sha256:7b2b818645a47eaa7e00fa92f29e6f5d246a430935eacbb47a96715c22209479
 - using hostNetworking
 
Configs:
```
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec:
  nodeSelector:
    company1.io/piraeus-deploy: 'true'
  patches:
    - target:
        kind: Service
        name: linstor-controller
      patch: |-
        apiVersion: v1
        kind: service
        metadata:
          name: linstor-controller
        spec:
          ipFamilyPolicy: SingleStack
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: host-network
  namespace: piraeus-datastore
spec:
  patches:
    - target:
        kind: Pod
        name: satellite
      patch: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: satellite
        spec:
          hostNetwork: true
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: drbd-module-loader-image-rhel9
spec:
  nodeSelector:
    feature.node.kubernetes.io/system-os_release.VERSION_ID.major: '9'
  patches:
    - target:
        kind: Pod
        name: satellite
      patch: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: satellite
        spec:
          initContainers:
          - name: drbd-module-loader
            image: quay.io/piraeusdatastore/drbd9-almalinux9
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: drbd-module-loader-image-rhel8
spec:
  nodeSelector:
    feature.node.kubernetes.io/system-os_release.VERSION_ID.major: '8'
  patches:
    - target:
        kind: Pod
        name: satellite
      patch: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: satellite
        spec:
          initContainers:
          - name: drbd-module-loader
            image: quay.io/piraeusdatastore/drbd9-almalinux8
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: satellite
spec:
  patches:
    - target:
        kind: ConfigMap
        name: satellite-config
      patch: |-
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: satellite-config
        data:
          linstor_satellite.toml: |
            [netcom]
              type = "plain"
              bind_address = "0.0.0.0"
              port = 3366
---
# storage mounted on nodes k8s1, k8s2, k8s3
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: file-pool
spec:
  nodeSelector:
    company1.io/piraeus-storage-thin: 'true'
  storagePools:
    - name: file-thin
      fileThinPool:
        directory: /mnt/piraeus-file-thin
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: file-thin
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
#volumeBindingMode: WaitForFirstConsumer
volumeBindingMode: Immediate
parameters:
  csi.storage.k8s.io/fstype: xfs
  storagePool: file-thin
  placementCount: '2'
#  allowRemoteVolumeAccess: 'true'
  allowRemoteVolumeAccess: 'false'
  property.linstor.csi.linbit.com/DrbdOptions/auto-quorum: suspend-io
  property.linstor.csi.linbit.com/DrbdOptions/Resource/on-no-data-accessible: suspend-io
  property.linstor.csi.linbit.com/DrbdOptions/Resource/on-suspended-primary-outdated: force-secondary
  property.linstor.csi.linbit.com/DrbdOptions/Net/rr-conflict: retry-connect
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-thin-volume
spec:
  resources:
    requests:
      storage: 1Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: file-thin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-logger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: volume-logger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: volume-logger
    spec:
      nodeName: k8s1.lab.company1.io
      terminationGracePeriodSeconds: 0
      containers:
        - name: volume-logger
          image: busybox
          args:
            - sh
            - -c
            - |
              echo "Hello from \$HOSTNAME, running on \$NODENAME, started at \$(date)" >> /volume/hello
              # We use this to keep the Pod running
              sleep infinity
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /volume
              name: replicated-volume
      volumes:
        - name: replicated-volume
          persistentVolumeClaim:
            claimName: file-thin-volume
```
