### ISSUE TITLE
Storage pool with the same name with different zfs backing volume

### ISSUE THREAD

**Issue by kiddouk** [piraeusdatastore/piraeus-operator#443]
Hi, 

I think that I am hitting an issue that sits in between piraeus-operator and linstor-server itself. I ask here first.

I have 2 nodes that have 1 SSD each. Each SSD has a ZFS storage pool. Naturally, I create 2 Linstor Storage Pool and use it.

```
kubectl linstor storage-pool create zfsthin node1 genericpool storage1
kubectl linstor storage-pool create zfsthin node2 genericpool storage2

kubect get sc linstor -o yaml

allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: linstor
  uid: 77a537a8-b277-4944-b4a6-04a9e24cfd0c
parameters:
  autoPlace: "2"
  storagePool: generic-pool
provisioner: linstor.csi.linbit.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

So far so good. 

Now, I want to add a second SSD to `node1`. I create a new ZFS storagepool on the whole disk. I want to create a new Linstor `Storage Pool `on node1 so that I can use my new disk with `"autoplace: 3"`.

```
kubectl linstor storage-pool create zfsthin node1 genericpool storage3

ERROR:
    Node: node1, Storage pool name: genericpool already exists.


```

Why can't I do this (beside the obvious database Index that requires unicity of host/poolname) ?

I could RAID my ZFS pools but I want to enjoy the `autoplace: 3`

What if I add an another ZFS pool to node2 and have 4 disks in generic-pool with `autoplace: 3` ?

Thanks,
