### ISSUE TITLE
Question: Replica placement strategy

### ISSUE THREAD

**Issue by boedy** [piraeusdatastore/piraeus-operator#467]
This perhaps is not a question for the piraeus-operator perse, but more Linstor in general, but posting here as others might find it useful. Please let me know if it would be better suited to post somewhere else.

We are attempting to run a large stretched cluster over multiple regions in which we use the Piraeus operator to provide a solid storage foundation for HA and disaster recovery.

The cluster is stretched over the following regions:
- eu-west
- eu-central
- us-west
- us-central

**Desired Result**
For most of our workloads we would want to have a placement count of 3 where the replica's should be placed in the following way:

- 2 replica's in the same zone - This is to protect against a node failure and support quick recovery
- 1 replica in a different zone, but same region - This third replica is there to protect against a datacenter failure and allow for disaster recovery

`linstor.csi.linbit.com/replicasOnSame` and `linstor.csi.linbit.com/replicasOnDifferent` are missing the flexibility to allow for this exact configuration. At least there is not one that I can think of directly.

**Possible workaround 1**
1. Label two nodes in the eu-west region with `storage-group=eu-a`
2. Label one node in the eu-central region with the same label `storage-group=eu-a`
3. Use the following storage-class:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: high-available
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: data-dir
  linstor.csi.linbit.com/placementCount: "3"
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
  linstor.csi.linbit.com/replicasOnSame: "storage-group"
```

I guess this would work, but we would always to create pairs of three nodes. Mistakes can be make quite easily during node configuration.

**Possible workaround 2**
Only use `linstor.csi.linbit.com/replicasOnSame: "topology.kubernetes.io/zone"`

Write an operator that will create an extra replica's in the same region but on a different zone. This basically will use the command
```
# create a replica in a different zone
linstor resource <node> <pvc>
```
If the affinity controller is used I believe this should work when the original datacenter goes down?

**Conclusion**
Maybe there is a simpeler solution which I haven't thought of yet. Hoping to get some idea's from others :)
