### ISSUE TITLE
How to resize pool?

### ISSUE THREAD

**Issue by ColonelBundy** [piraeusdatastore/piraeus-operator#481]
I have created a lvm thin pool in the sateliteconfiguration like so:

```yaml
spec:
  storagePools:
  - lvmThinPool:
      volumeGroup: vg1
    name: vg1
    source:
      hostDevices:
      - /dev/sdc
```

The sdc device is a proxmox disk sized at 10gb. So now I wish to resize this to 20gb and I've done so in promxox and rescanned the device in the host os and updated it accordingly but the change is not reflected in linstor. 
I thought I had to update the lvm pool manually but I cannot find any vgs.

How do you tell linstor to rescan/update the pool?
