### ISSUE TITLE
How to add an additional device to linstorsatellite.spec.storagepools.source

### ISSUE THREAD

**Issue by Nosmoht** [piraeusdatastore/piraeus-operator#503]
Hi All,

i would like to add an additional disk to my storagepool.

Current config is like this:
```yaml
...
  storagePools:
  - lvmPool: {}
    name: lvm-thick
    source:
      hostDevices:
      - /dev/sdb
```

When i try to modify the `hostDevices` and add disk `/dev/sdc` i get the following error:
```shell
# * spec.storagePools.0.source: Forbidden: Cannot change source
```

So the question is: How can i add an additional disks to the already existing pool?
