### ISSUE TITLE
piraeus-operator not reconsiling `ContainerStatusUnknown` containers

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/piraeus-operator#505]
Just tried v2 on talos:

```
# kubectl get pod -n piraeus-datastore
NAME                                                   READY   STATUS                   RESTARTS      AGE
ha-controller-6k6kp                                    1/1     Running                  0             13h
ha-controller-lspwh                                    1/1     Running                  0             13h
ha-controller-mjj7t                                    1/1     Running                  0             13h
ha-controller-ng8f9                                    1/1     Running                  1 (13h ago)   13h
ha-controller-xbrs7                                    1/1     Running                  0             13h
linstor-controller-6c8f8dc47-9g95f                     1/1     Running                  0             21m
linstor-csi-controller-59b9968b86-pknzx                7/7     Running                  0             13h
linstor-csi-node-6b95g                                 3/3     Running                  0             13h
linstor-csi-node-cb5m5                                 3/3     Running                  0             13h
linstor-csi-node-clrks                                 0/3     Init:0/1                 0             13h
linstor-csi-node-lzlx5                                 3/3     Running                  0             13h
linstor-csi-node-mrw9g                                 3/3     Running                  0             13h
piraeus-operator-controller-manager-85564c495b-fv8kk   1/1     Running                  0             13h
piraeus-operator-gencert-c8c6c95d5-cqzfr               1/1     Running                  0             13h
talos-5c2-kma                                          2/2     Running                  0             13h
talos-bab-pwr                                          2/2     Running                  0             13h
talos-ljz-hcq                                          0/2     ContainerStatusUnknown   0             13h
talos-wpb-0z8                                          2/2     Running                  0             13h
talos-xjf-f8n                                          2/2     Running                  0             13h
```

```yaml
# kubectl describe pod talos-ljz-hcq -n piraeus-datastore
Name:             talos-ljz-hcq
Namespace:        piraeus-datastore
Priority:         0
Service Account:  satellite
Node:             talos-ljz-hcq/192.168.88.210
Start Time:       Fri, 21 Jul 2023 15:54:06 +0000
Labels:           app.kubernetes.io/component=linstor-satellite
                  app.kubernetes.io/instance=linstorcluster
                  app.kubernetes.io/managed-by=piraeus-operator
                  app.kubernetes.io/name=piraeus-datastore
                  app.kubernetes.io/version=v2-61b05f3936942f1ccd6df8dbda5f6ee72976f043
Annotations:      kubectl.kubernetes.io/default-container: linstor-satellite
Status:           Failed
Reason:           Terminated
Message:          Pod was terminated in response to imminent node shutdown.
IP:
IPs:              <none>
Controlled By:    LinstorSatellite/talos-ljz-hcq
Containers:
  linstor-satellite:
    Container ID:
    Image:         quay.io/piraeusdatastore/piraeus-server:v1.23.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      startSatellite
    State:          Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was terminated
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      JAVA_OPTS:  -Djdk.tls.acknowledgeCloseNotify=true
    Mounts:
      /dev from dev (rw)
      /etc/linstor from satellite-config (ro)
      /etc/lvm/archive from etc-lvm-archive (rw)
      /etc/lvm/backup from etc-lvm-backup (rw)
      /run from run (rw)
      /run/lock from run-lock (rw)
      /tmp from tmp (rw)
      /var/lib/drbd from var-lib-drbd (rw)
      /var/lib/linstor.d from var-lib-linstor-d (rw)
      /var/log/linstor-satellite from var-log-linstor-satellite (rw)
  drbd-reactor:
    Container ID:
    Image:          quay.io/piraeusdatastore/drbd-reactor:v1.2.0
    Image ID:
    Port:           9942/TCP
    Host Port:      0/TCP
    State:          Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was terminated
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/drbd-reactor.d from reactor-config (ro)
Conditions:
  Type               Status
  DisruptionTarget   True
  Initialized        True
  Ready              False
  ContainersReady    False
  PodScheduled       True
Volumes:
  etc-lvm-backup:
    Type:          HostPath (bare host directory volume)
    Path:          /var/etc/lvm/backup
    HostPathType:  DirectoryOrCreate
  etc-lvm-archive:
    Type:          HostPath (bare host directory volume)
    Path:          /var/etc/lvm/archive
    HostPathType:  DirectoryOrCreate
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  Directory
  var-lib-linstor-d:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/linstor.d
    HostPathType:  DirectoryOrCreate
  var-lib-drbd:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/drbd
    HostPathType:  DirectoryOrCreate
  var-log-linstor-satellite:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/linstor-satellite
    HostPathType:  DirectoryOrCreate
  satellite-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      talos-ljz-hcq-satellite-config
    Optional:  false
  reactor-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      talos-ljz-hcq-reactor-config
    Optional:  false
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  run-lock:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  run:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:   <unset>
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     drbd.linbit.com/force-io-error:NoSchedule
                 drbd.linbit.com/lost-quorum:NoSchedule
                 node-role.kubernetes.io/control-plane:NoSchedule
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:          <none>
```

simple removing of the container makes it running again
