### ISSUE TITLE
failed to find images.yaml in image configuration config map

### ISSUE THREAD

**Issue by giovannicandido** [piraeusdatastore/piraeus-operator#510]
Hi,
I'm trying to install in a oracle linux kubernetes cluster. Its based on red hat 8.7

I get the error:

`failed to find images.yaml in image configuration config map`

Do I miss something?

Here is my configuration:

```
etcd:
  enabled: false
operator:
  controller:
    dbConnectionURL: k8s
  satelliteSet:
    kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-centos8
    storagePools:
      lvmThinPools:
      - name: lvm-thin
        thinVolume: thinpool
        volumeGroup: ""
        devicePaths:
          - /dev/sdb
installCRDs: true
```

Instalation:

```
git clone --branch v2 https://github.com/piraeusdatastore/piraeus-operator
cd piraeus-operator
helm install --values ..\values.yml --create-namespace -n piraeus-datastore piraeus-operator ./charts/piraeus --set installCRDs=true
helm -n piraeus-datastore upgrade piraeus-operator ./charts/piraeus --reuse-values --set installCRDs=true
```
