### ISSUE TITLE
Does piraeus support volumeMode block pv?

### ISSUE THREAD

**Issue by Icedroid** [piraeusdatastore/piraeus-operator#515]
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc-1
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: piraeus-local-dflt-r2
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: local-pod
spec:
  containers:
    - name: test
      image: registry.eecos.cn:7443/ecf-edge/tools/linux-utils
      # Just spin & wait forever
      command: [ "sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeDevices:
        - devicePath: /dev/xvda
          name: csivol
      imagePullPolicy: IfNotPresent
  volumes:
    - name: csivol
      persistentVolumeClaim:
        claimName: local-pvc-1
  restartPolicy: OnFailure
```

After create, I exec into container, I found /dev/xvda can't not write:

bash-5.1# dd if=/dev/zero of=/dev/xvda bs=1M count=100
dd: can't open '/dev/xvda': Read-only file system
