### ISSUE TITLE
Multiple external controllers

### ISSUE THREAD

**Issue by euh2** [piraeusdatastore/piraeus-operator#527]
I set up a external HA cluster. Now I wonder how the operator is supposed to be configured for that. The [docs](https://github.com/piraeusdatastore/piraeus-operator/blob/04d6b791971821db9bdaf0e566d82198498bf6ed/docs/how-to/external-controller.md) say:
```yaml
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec:
  externalController:
    url: http://linstor-controller.example.com:3370
```
`url:` doesn't seem to accept a list of controllers like other clients do. I could set up a HAPROXY with availability checking in front. But maybe there is a simpler solution?
