### ISSUE TITLE
doc: Can ha-controller options be set through the Helm chart?

### ISSUE THREAD

**Issue by mattlqx** [piraeusdatastore/piraeus-operator#529]
I have an issue where I'm running about 22 volumes and am getting the issue where if one volume loses quorum (or is just being created), ha-controller will taint one of my nodes and cause pods to redeploy ultimately causing a bunch of turbulence.

Can I disable or set options for ha-controller using Helm chart in the repo? I'm not seeing this documented at all. Thanks.

**Comment by mattlqx** [comment]
This is on piraeus-operator v2 using the chart from the `v2` branch.

**Comment by WanzenBug** [comment]
Using the following [`patch`](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorcluster.md#specpatches) should do the trick
```yaml
  - patch: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: ha-controller
      $patch: delete
    target:
      kind: DaemonSet
      name: ha-controller
```
