### ISSUE TITLE
PVC Created from Snapshot is empty

### ISSUE THREAD

**Issue by CrimsonFez** [piraeusdatastore/piraeus-operator#582]
Hello,
I'm using operator v2 and lvmthin.
I ran into this issue and I haven't figured it out. When I create a PVC based on a volume snapshot or the volume snapshot content, the resulting PVC has no data, it is a new filesystem.
I don't remember this being an issue a few weeks ago when I did it before.
I was able to restore my data manually from the lvm thin snapshot, so that was created properly.
It seams to me that there is some issue with provisioning based off of snapshots, volume cloning works fine.
I did update the snapshot external provisioner a few days ago so maybe that has something to do with it.
Any help is appreciated, thanks in advance!

**Comment by CrimsonFez** [comment]
I'm a big idiot...

wrong
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snaptest
  namespace: keycloak-prod
spec:
  dataSource:
    kind: VolumeSnapshot
    name: test1
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
```

right
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snaptest
  namespace: keycloak-prod
spec:
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: test1
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
```

i didnt add the apiGroup
