### ISSUE TITLE
Unsure of how to specify the satellite image in v2

### ISSUE THREAD

**Issue by jonathon2nd** [piraeusdatastore/piraeus-operator#598]
Hello!

In v1 our helm values were as follows.

```
---
operator:
  controller:
    enabled: false
  satelliteSet:
    kernelModuleInjectionImage: quay.io/piraeusdatastore/drbd9-centos8:v9.2.2
    satelliteImage: quay.io/piraeusdatastore/piraeus-server:v1.20.0-1
...
```

I have migrated our test cluster to v2 following this [guide](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/how-to/upgrade/index.md), but I am currenlty seeing no way to specify the satellite image to work with our separate linstor cluster.

I have checked [satellite config](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/reference/linstorsatelliteconfiguration.md), and the [helm values](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/charts/piraeus/values.yaml)

Thanks in advance!

**Comment by jonathon2nd** [comment]
I found where in the configmap to manually modify it

```
apiVersion: v1
data:
  0_piraeus_datastore_images.yaml: >
    ---
...
    components:
      linstor-controller:
        tag: v1.25.1
        image: piraeus-server
      linstor-satellite:
        tag: v1.20.0-1
        image: piraeus-server
...
```

But it wants to be overwritten by helm.
![image](https://github.com/piraeusdatastore/piraeus-operator/assets/52681917/e3e08dae-a588-494b-8d0a-c0160c851b09)

**Comment by jonathon2nd** [comment]
Also needed to do the same thing for drbd. We are using rocky so I just changed the fall back and it is all working now.

Need to be able to manage this in helm or a crd so that helm updates do not nuke needed changes. 
![image](https://github.com/piraeusdatastore/piraeus-operator/assets/52681917/29d5563c-9165-49d2-90c5-82a9870a01df)

**Comment by WanzenBug** [comment]
You can use the [`imageConfigOverride`](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/charts/piraeus/values.yaml#L101-L108) in the helm values like this:
```
imageConfigOverride:
- base: example.com/piraeus
  components:
    linstor-satellite:
      image: piraeus-server
      tag: v1.20.0-1
    drbd-module-loader:
      image: drbd9-centos8
      tag: v9.2.6
```

Also, please consider upgrading, I'm not sure how well the operator will work with a LINSTOR version from 2022
