### ISSUE TITLE
Helm chart with TLS does not create Issuer

### ISSUE THREAD

**Issue by OlivierMary** [piraeusdatastore/piraeus-operator#613]
Helm chart must create this Issuer

```

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: piraeus-root
  namespace: piraeus-datastore
spec:
  selfSigned: { }


```
