### ISSUE TITLE
StorageException: Failed to pvcreate on device: /dev/sdb

### ISSUE THREAD

**Issue by S3LL1G28** [piraeusdatastore/piraeus-operator#639]
Hi,

I'm usiong kubernetes 1.28.8

I'm using your helm to deploy piraeus-2.2.0 (operator) and linstor-cluster-1.0.1.

I Have workers (ubuntu 22.04) with nodeselector where a second disk is available for using with drbd.

Everything is in running state but LVM part is not working.

if i use this command: 
```
kubectl -n piraeus exec -it deploy/linstor-controller -- linstor error-reports list
```
I see that pvcreate, vgcreate is failing: StorageException: Failed to pvcreate on device: /dev/sdb

Here is my value configuration for linstor-cluster:

``` yaml
---
# Source: linstor-cluster/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-r01
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    helm.sh/chart: linstor-cluster-1.0.1
    app.kubernetes.io/name: linstor-cluster
    app.kubernetes.io/instance: piraeus-cluster
    app.kubernetes.io/version: "v2.4.0"
    app.kubernetes.io/managed-by: Helm
provisioner: linstor.csi.linbit.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  linstor.csi.linbit.com/allowRemoteVolumeAccess: "false"
  linstor.csi.linbit.com/autoPlace: "1"
  linstor.csi.linbit.com/storagePool: lvm-thin
---
# Source: linstor-cluster/templates/linstorcluster.yaml
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: piraeus-cluster-linstor-cluster
  labels:
    helm.sh/chart: linstor-cluster-1.0.1
    app.kubernetes.io/name: linstor-cluster
    app.kubernetes.io/instance: piraeus-cluster
    app.kubernetes.io/version: "v2.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  nodeSelector:
    storage: piraeus
---
# Source: linstor-cluster/templates/linstorsatelliteconfiguration.yaml
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: piraeus-cluster-linstor-cluster-worker-config
  labels:
    helm.sh/chart: linstor-cluster-1.0.1
    app.kubernetes.io/name: linstor-cluster
    app.kubernetes.io/instance: piraeus-cluster
    app.kubernetes.io/version: "v2.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  nodeSelector:
    storage: piraeus
  storagePools:
  - lvmThinPool:
      thinPool: thin
      volumeGroup: piraeus
    name: lvm-thin
    properties:
    - name: StorDriver/LvcreateOptions
      value: --compression n
    source:
      hostDevices:
      - /dev/sdb
      
```
Tell me if you can help me and if you need more informations

Thank you.
