### ISSUE TITLE
Linstor, installed via Piraeus operator in Kubernetes cluster, disables LVM monitoring

### ISSUE THREAD

**Issue by dmrub** [piraeusdatastore/piraeus-operator#644]
Priaeus operator: v2.5.0
Piraeus server: v1.27.0
Linstor is installed with the following satellite configuration
```yaml
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: linstor-fast
spec:
  internalTLS:
    certManager:
      kind: Issuer
      name: linstor-internal-ca
  storagePools:
  - name: vg00-linstor
    lvmThinPool:
      volumeGroup: vg00
      thinPool: linstor   
```
After the installation on all nodes belonging to the cluster, I see the following error message from dmeventd:
```
Apr 15 15:25:08 k8s-m2 dmeventd[510]: dmeventd ready for processing.
Apr 15 15:25:08 k8s-m2 lvm[510]: Monitoring thin pool vg00-linstor.
Apr 15 15:39:05 k8s-m2 lvm[510]: Cannot resize logical volume vg00/linstor with active component LV(s).
Apr 15 15:39:05 k8s-m2 lvm[510]: Failed command for vg00-linstor.
Apr 15 15:39:05 k8s-m2 lvm[510]: Invalid target type.
Apr 15 15:39:05 k8s-m2 lvm[510]: device-mapper: waitevent ioctl on  LVM-GESmqya2yM2SsNLq8tV8e7azMA8NDvGNUYToXRoepSR8le7ljnfMlR9HEdJuHQrF-tpool failed: No such device or address
Apr 15 15:39:05 k8s-m2 lvm[510]: vg00-linstor disappeared, detaching.
Apr 15 15:39:05 k8s-m2 dmeventd[510]: No longer monitoring thin pool vg00-linstor.

```
This means that LVM does not resize thin volumes, even if automatic expansion is enabled:
```
root@k8s-m2:/home/devops-core# lvmconfig --type diff
activation {
	snapshot_autoextend_threshold=75
	thin_pool_autoextend_threshold=70
}
devices {
	issue_discards=1
}
root@k8s-m2:/home/devops-core# lvs
  LV                                             VG   Attr       LSize  Pool    Origin Data%  Meta%  Move Log Cpy%Sync Convert
  linstor                                        vg00 twi-aotzD- 20,00g                100,00 44,14                           
  pvc-0ad453e9-ead4-4d94-b2de-7d5a7f3abadc_00000 vg00 Vwi-a-tz--  8,00g linstor        3,07                                   
  pvc-32a9b1ff-9cfb-428b-9116-5c5d0d8364cd_00000 vg00 Vwi-a-tz-- 10,00g linstor        2,41                                   
  pvc-78ae7fd6-bbc0-4902-824f-930179db89e0_00000 vg00 Vwi-aotz--  1,00g linstor        4,80                                   
  pvc-9b55563b-dbb1-4098-a832-41bc5a7ac3d7_00000 vg00 Vwi-a-tz-- 10,00g linstor        98,82                                  
  pvc-e36b20eb-7c24-47e3-b0ec-52164f359d77_00000 vg00 Vwi-aotz--  5,00g linstor        2,91                                   
  pvc-eda4d861-b19c-43ff-b540-30e949e72473_00000 vg00 Vwi-a-tz-- 10,00g linstor        94,31                                  
  root                                           vg00 -wi-ao---- 60,00g                                                       

```
I assume that Linstor should not deactivate monitoring.

**Comment by WanzenBug** [comment]
This is most likely related to the following lvmconfig options:
```
activation {
  monitoring 0
}
```

This gets set in our dockerfiles: https://github.com/piraeusdatastore/piraeus/blob/master/dockerfiles/piraeus-server/Dockerfile#L61

The reason we set this is because otherwise the lvm tools in the container will try to spawn dmeventd inside the container, which leads to all kinds of issues. We also can't just pass through whatever socket it uses, because not all users make use of LVM or have it installed.

You may be able to update the `podTemplate` for your satellites to:
1. Pass through whatever socket is used by dmeventd
2. Override the lvmconfig with your own to ensure the lvm tools activate monitoring.

**Comment by dmrub** [comment]
I am not 100% sure what to do. Should I mount /run/dmeventd-server and /run/dmeventd-client sockets in the satellites with podTemplate and then change the lvm configuration in the container and enable monitoring? 

Also in your documentation (see https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#_configuring_storage_nodes) you write:

> Set the thin-provisioned logical volume’s metadata space to a reasonable size because if it becomes full it can be difficult to resize. For this reason, you might also want to configure monitoring or automatic extension of your LVM thin-provisioned logical volumes. Refer to the “Size of pool metadata LV” section in man lvmthin for more details

So I assume that the built-in LVM mechanisms for automatically extending volumes should work. I have not found anything in the LINSTOR documentation that says otherwise.

**Comment by WanzenBug** [comment]
> I am not 100% sure what to do. Should I mount /run/dmeventd-server and /run/dmeventd-client sockets in the satellites with podTemplate and then change the lvm configuration in the container and enable monitoring?

Yes, that was what I was suggesting.

**Comment by dmrub** [comment]
Thanks, the monitoring is starting to work when I use this Sattelite configuration. Would be nice if you could add it to the documentation. Also, I need to explicitly override in the yaml the "command" attribute with entrypoint commands from the container. However, your Dockerfile might change in the future, which would require changes in this YAML.

```yaml
---    
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: linstor-fast
spec:
  internalTLS:
    certManager:
      name: linstor-internal-ca
      kind: Issuer
  storagePools:
    - name: vg00-linstor
      lvmThinPool:
        volumeGroup: vg00
        thinPool: linstor
  podTemplate:
    spec:
      containers:
        - name: linstor-satellite
          #args:
          #  - startSatellite
          command:
            - sh
            - -c
            - |-
              set -xe;
              lvmconfig --type current --mergedconfig --config 'activation { monitoring = 1 }' > /etc/lvm/lvm.conf.new && mv /etc/lvm/lvm.conf.new /etc/lvm/lvm.conf;
              /usr/bin/k8s-await-election /usr/bin/piraeus-entry.sh startSatellite;
          securityContext:
            readOnlyRootFilesystem: false
          volumeMounts:
            - mountPath: /run/dmeventd-server
              name: dmeventd-server
            - mountPath: /run/dmeventd-client
              name: dmeventd-client
      volumes:
        - name: dmeventd-server
          hostPath:
            path: /run/dmeventd-server
        - name: dmeventd-client
          hostPath:
            path: /run/dmeventd-client
```
