### ISSUE TITLE
make master node only for DISKLESS as TieBreaker 

### ISSUE THREAD

**Issue by yeshl** [piraeusdatastore/piraeus-operator#653]
i want make master node only for DISKLESS as TieBreaker ,  whether I configure spec.nodeSelector/spec.nodeAffinity in linstorcluster or LinstorSatelliteConfiguration，it is not working！lost master satellite！
```
WARNING:
Description:
    No active connection to satellite 'master0.k8s'
Details:
    The controller is trying to (re-) establish a connection to the satellite. The controller stored the changes and as soon the satellite is connected, it will receive this update.
 ```

**Comment by WanzenBug** [comment]
Is the satellite actually running on master0.k8s? Is there any kind of firewall or similar that would prevent the connection?

**Comment by yeshl** [comment]
I found the solution：
```
1. piraeus-operator and linstorcluster
       tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

2. LinstorSatelliteConfiguration
  nodeSelector:
    kubernetes.io/os: linux
    zwsx.io/storage: "yes"
  patches:
    - target:
        kind: Pod
        name: satellite
      patch: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: satellite
        spec:
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule    
```

**Comment by lucacalcaterra** [comment]
> I found the solution：
> 
> ```
> 1. piraeus-operator and linstorcluster
>        tolerations:
>         - key: node-role.kubernetes.io/master
>           operator: Exists
>           effect: NoSchedule
>         - key: node-role.kubernetes.io/control-plane
>           operator: Exists
>           effect: NoSchedule
> 
> 2. LinstorSatelliteConfiguration
>   nodeSelector:
>     kubernetes.io/os: linux
>     zwsx.io/storage: "yes"
>   patches:
>     - target:
>         kind: Pod
>         name: satellite
>       patch: |
>         apiVersion: v1
>         kind: Pod
>         metadata:
>           name: satellite
>         spec:
>           tolerations:
>             - key: node-role.kubernetes.io/master
>               operator: Exists
>               effect: NoSchedule
>             - key: node-role.kubernetes.io/control-plane
>               operator: Exists
>               effect: NoSchedule    
> ```

I need too :-) Can you specify ? piraeus-operator, where ? Can you share your config for this ? Which version do you use ? Thanks !

**Comment by Northcode** [comment]
To anyone ending up here because you are trying to do the same thing on 2.9.0
The patch method does not seem to work anymore.
A new method of adding tolerations was introduced in LinstorCluster: https://piraeus.io/docs/v2.9.0/reference/linstorcluster/#spectolerations

Note that I had to remove any toleration patches I had set before this would work.
So... the following was my solution:
```
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
      operator: Exists
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool
spec:
  storagePools:
    - name: zpool
      zfsThinPool:
        zPool: tank/piraeus
```

NOTE: the "patches" sections are REMOVED
the operator now seems to schedule ha-controller, csi-node and sattelite pods correctly:
```
~/p/k3s-testing $ k get pods -o wide
NAME                                                   READY   STATUS    RESTARTS      AGE     IP            NODE          NOMINATED NODE   READINESS GATES
ha-controller-2jsrq                                    1/1     Running   0             9m52s   10.42.0.144   k3s-master    <none>           <none>
ha-controller-fh7t9                                    1/1     Running   0             10m     10.42.1.66    k3s-agent-1   <none>           <none>
ha-controller-lcwng                                    1/1     Running   0             10m     10.42.2.209   k3s-agent-2   <none>           <none>
linstor-controller-d4d879885-cqrxd                     1/1     Running   0             43s     10.42.0.145   k3s-master    <none>           <none>
linstor-csi-controller-56f888b446-4hshs                7/7     Running   0             10m     10.42.0.142   k3s-master    <none>           <none>
linstor-csi-node-77655                                 3/3     Running   0             6s      10.42.1.68    k3s-agent-1   <none>           <none>
linstor-csi-node-mqjjm                                 3/3     Running   0             11s     10.42.0.147   k3s-master    <none>           <none>
linstor-csi-node-s8t22                                 3/3     Running   0             8s      10.42.2.211   k3s-agent-2   <none>           <none>
linstor-satellite.k3s-agent-1-4rg6f                    2/2     Running   0             32s     10.42.1.67    k3s-agent-1   <none>           <none>
linstor-satellite.k3s-agent-2-ph8xq                    2/2     Running   0             32s     10.42.2.210   k3s-agent-2   <none>           <none>
linstor-satellite.k3s-master-htcxn                     2/2     Running   0             32s     10.42.0.146   k3s-master    <none>           <none>
piraeus-operator-controller-manager-7c45b64cc5-d9ccp   1/1     Running   1 (68m ago)   83m     10.42.0.133   k3s-master    <none>           <none>
piraeus-operator-gencert-6fbfc4ffb5-cjbwv              1/1     Running   2 (67m ago)   83m     10.42.1.49    k3s-agent-1   <none>           <none>
```

My nodes show up and the volume is Diskless on the control-plane:
```
~/p/k3s-testing $ kubectl -n piraeus-datastore exec deploy/linstor-controller -- linstor node list
+-------------------------------------------------------------+
| Node        | NodeType  | Addresses                | State  |
|=============================================================|
| k3s-agent-1 | SATELLITE | 10.42.1.67:3366 (PLAIN)  | Online |
| k3s-agent-2 | SATELLITE | 10.42.2.210:3366 (PLAIN) | Online |
| k3s-master  | SATELLITE | 10.42.0.146:3366 (PLAIN) | Online |
+-------------------------------------------------------------+
~/p/k3s-testing $ kubectl -n piraeus-datastore exec deploy/linstor-controller -- linstor resource list-volumes
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Resource                                 | Node        | StoragePool          | VolNr | MinorNr | DeviceName    | Allocated | InUse  |    State | Repl           |
|==================================================================================================================================================================|
| pvc-075b9cb5-b09a-4d62-b36d-d9524950855e | k3s-agent-1 | zpool                |     0 |    1000 | /dev/drbd1000 |    56 KiB | Unused | UpToDate | Established(2) |
| pvc-075b9cb5-b09a-4d62-b36d-d9524950855e | k3s-agent-2 | zpool                |     0 |    1000 | /dev/drbd1000 |    56 KiB | InUse  | UpToDate | Established(2) |
| pvc-075b9cb5-b09a-4d62-b36d-d9524950855e | k3s-master  | DfltDisklessStorPool |     0 |    1000 | /dev/drbd1000 |           | Unused | Diskless | Established(2) |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

I'm unsure if it saying "Diskless" here means its just going to be used as a TieBreaker, but considering the node has a taint the pods mounting the pvc are never going to be scheduled to it anyway, so I'm guessing thats functionally the same anyway?

I'm a bit new to piraeus so if any of the devs want to chime in to explain that would be great.

**Comment by WanzenBug** [comment]
You have basically got it right. 

1. With the `LinstorCluster` resource, you set the nodes that form the LinstorCluster. This is done using `nodeAffinity`, `nodeSelector` and `tolerations` settings. See [the reference docs](https://piraeus.io/docs/v2.9.0/reference/linstorcluster/).

2. With the `LinstorSatelliteConfiguration`, you can apply storage pools to all or only a subset of all LinstorCluster nodes. You configure your storage pool only on the worker nodes, and the master node can act as a tie breaker.

>  So... the following was my solution:

You probably want to to update the `LinstorSatelliteConfiguration` to include a `nodeSelector` so that the storage pool is not configured on the k8s-master node. Something like:

```
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool
spec:
  nodeSelector:
    zwsx.io/storage: "yes"
  storagePools:
    - name: zpool
      zfsThinPool:
        zPool: tank/piraeus
```
