### ISSUE TITLE
setup fails for minikube

### ISSUE THREAD

**Issue by drev74** [piraeusdatastore/piraeus-operator#662]
I'm trying to setup Piraeus cluster for Minikube, using host mounts: 
```sh
minikube start --mount-string="/run/udev:/run/udev" "/run/dbus:/run/dbus" --mount
```
cluster.yml
```yaml
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
```
Getting an error:
```sh
Normal   Scheduled    5m3s  default-scheduler  Successfully assigned piraeus-datastore/linstor-satellite.minikube-bqkdn to minikube
Warning  FailedMount  53s (x10 over 5m3s)  kubelet MountVolume.SetUp failed for volume "systemd-bus-socket" : hostPath type check failed: /run/dbus/system_bus_socket is not a socket file
```
Versions:
OS: Ubuntu 22.04
Minikube: v1.33.0
Kubectl: 1.30.0
Piraeus: v2.5.1
