### ISSUE TITLE
Talos Drbd module

### ISSUE THREAD

**Issue by dragon2611** [piraeusdatastore/piraeus-operator#692]
I think the docs for talos need updating as it seems installing extensions via machine config is deprecated.

You need to build/deploy install image with DRBD support at https://factory.talos.dev/

The section
```
machine:
  install:
    extensions:
      - image: ghcr.io/siderolabs/drbd:9.2.0-v1.3.6
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
      
```
   becomes
   
```
machine:
  kernel:
    modules:
      - name: drbd
        parameters:
          - usermode_helper=disabled
      - name: drbd_transport_tcp
```

As you still need to set the Kernel module parameter, or you won't get any volumes created.
