### ISSUE TITLE
LVM striping

### ISSUE THREAD

**Issue by maxpain** [piraeusdatastore/piraeus-operator#714]
Hello. How to enable LVM striping in this configuration?

```yaml
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: talos-loader-override
spec:
  storagePools:
    - name: nvme-lvm
      lvmPool: {}
      source:
        hostDevices:
          - /dev/nvme0n1
          - /dev/nvme1n1
```
