### ISSUE TITLE
Ram leak?

### ISSUE THREAD

**Issue by jonathon2nd** [piraeusdatastore/piraeus-operator#792]
I seem to be having a memory leak issue on the piraeus operator pod. I have had to kill it a few times already

REPO URL
[https://github.com/piraeusdatastore/piraeus-operator.git](https://github.com/piraeusdatastore/piraeus-operator)
TARGET REVISION
[v2.8.0](https://github.com/piraeusdatastore/piraeus-operator/tree/v2.8.0)
PATH
[charts/piraeus](https://github.com/piraeusdatastore/piraeus-operator/tree/v2.8.0/charts/piraeus)

Values
```
---
installCRDs: true
imageConfigOverride:
- base: quay.io/piraeusdatastore
  components:
    linstor-satellite:
      image: piraeus-server
      tag: v1.29.0
tls:
  certManagerIssuerRef:
    name: step-issuer
    kind: StepClusterIssuer
    group: certmanager.step.sm
```
I downloaded the operator logs, but there was nothing useful in there

![Image](https://github.com/user-attachments/assets/909b2103-8f3d-4e24-b372-a35ea05d5f65)
