### ISSUE TITLE
Snapshot stuck in state "DELETING" after running backup with external tool velero with option --snapshot-move-data

### ISSUE THREAD

**Issue by ValentinChirikov** [piraeusdatastore/piraeus-operator#798]
Hello everyone, 
we are trying to set-up velero backup's in local experiment k8s cluster (vanilla k8s, piraeus datastore, zfs, ubuntu 24) . And we encountered a problem - after velero proceeds with backup, snapshot stuck at stage DELETING, the logs of linstor controller show the error below:

```
ERROR REPORT 67E4E628-34119-000036

============================================================

Application:                        LINBIT? LINSTOR
Module:                             Satellite
Version:                            1.30.4
Build ID:                           bef74a44609cb592c5efad2e707b50e696623c61
Build time:                         2025-02-03T15:48:28+00:00
Error time:                         2025-03-27 12:39:50
Node:                               r320
Thread:                             DeviceManager

============================================================

Reported error:
===============

Category:                           LinStorException
Class name:                         StorageException
Class canonical name:               com.linbit.linstor.storage.StorageException
Generated at:                       Method 'checkExitCode', Source file 'ExtCmdUtils.java', Line #69

Error message:                      Failed to delete zfs snapshot

Error context:
        An error occurred while processing snapshot 'snapshot-f89e9a27-6e44-407a-a83e-4d09c98377ac' of resource 'pvc-1b679cf3-693b-4d15-b758-7c5ebc9eba06'
ErrorContext:
  Details:     Command 'zfs destroy poolk8s/pvc-1b679cf3-693b-4d15-b758-7c5ebc9eba06_00000@snapshot-f89e9a27-6e44-407a-a83e-4d09c98377ac' returned with exitcode 1.

Standard out:


Error message:
cannot destroy 'poolk8s/pvc-1b679cf3-693b-4d15-b758-7c5ebc9eba06_00000@snapshot-f89e9a27-6e44-407a-a83e-4d09c98377ac': snapshot has dependent clones
use '-R' to destroy the following datasets:
poolk8s/pvc-f51d2fd5-c6a6-45cd-951b-f376ede95555_00000




Call backtrace:

    Method                                   Native Class:Line number
    checkExitCode                            N      com.linbit.extproc.ExtCmdUtils:69
    genericExecutor                          N      com.linbit.linstor.storage.utils.Commands:103
    genericExecutor                          N      com.linbit.linstor.storage.utils.Commands:63
    delete                                   N      com.linbit.linstor.layer.storage.zfs.utils.ZfsCommands:104
    deleteSnapshotImpl                       N      com.linbit.linstor.layer.storage.zfs.ZfsProvider:490
    deleteSnapshotImpl                       N      com.linbit.linstor.layer.storage.zfs.ZfsProvider:75
    deleteSnapshot                           N      com.linbit.linstor.layer.storage.AbsStorageProvider:896
    processSnapshotVolumes                   N      com.linbit.linstor.layer.storage.AbsStorageProvider:451
    processSnapshot                          N      com.linbit.linstor.layer.storage.StorageLayer:335
    processGeneric                           N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:1411
    processSnapshot                          N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:1379
    processSnapshots                         N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:738
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:222
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:333
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:1148
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:778
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:674
    run                                      N      java.lang.Thread:840


END OF ERROR REPORT.
```

so the reason seems to be that destroy command is called without -R for some reason. 
But if snapshot deletion command is called manually, snapshot deletes.  The below command helps us so far:
```
kubectl -n piraeus-datastore exec deploy/linstor-controller -- linstor s l -p | tail -n +4 | head -n -1 | awk -F "|" '{print $2 $3;}' | xargs -n 2 kubectl -n piraeus-datastore exec deploy/linstor-controller -- linstor s d
```

storage configuration:
```
kubectl apply -f - <<EOF
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: poolk8s
spec:
  nodeSelector:
    kubernetes.io/hostname: r320
  storagePools:
    - name: poolk8s
      zfsPool:
        zPool: poolk8s
EOF
```

```
kubectl apply -f - <<EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: poolk8s
provisioner: linstor.csi.linbit.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: poolk8s
  linstor.csi.linbit.com/placementCount: "1"
  linstor.csi.linbit.com/disklessOnRemaining: "false"
  linstor.csi.linbit.com/layerList: "storage"
EOF
```
