### ISSUE TITLE
piraeus-operator 通过  kustomization 部署，怎么指定 imagePullSecrets？

### ISSUE THREAD

**Issue by junneyang** [piraeusdatastore/piraeus-operator#801]

**Comment by WanzenBug** [comment]
Instead of deploying directly from `https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.8.0`, use the following `kustomization.yaml`:

```yaml
resources:
- https://github.com/piraeusdatastore/piraeus-operator//config/default?ref=v2.8.0

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller-manager
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: pull-secret
          containers:
          - name: manager
            env:
              - name: PULL_SECRET
                value: pull-secret
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gencert
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: pull-secret
```
