### ISSUE TITLE
"error":"failed to create typed patch object: .spec.ipFamilyPolicy: field not declared in schema"

### ISSUE THREAD

**Issue by junneyang** [piraeusdatastore/piraeus-operator#803]
```
kubectl apply -f - <<EOF
> apiVersion: piraeus.io/v1
> kind: LinstorCluster
> metadata:
>   name: linstorcluster
> spec: {}
> EOF
```
执行之后无效，piraeus-operator-controller-manager 有报错日志：

![Image](https://github.com/user-attachments/assets/09059673-61ed-48f2-a172-1a3b9477732b)

**Comment by WanzenBug** [comment]
What Kubernetes version are you using?

**Comment by junneyang** [comment]
> What Kubernetes version are you using?

v1.19.0

**Comment by WanzenBug** [comment]
We generally only support v1.20 and up. You might be able to use a [`patch`](https://piraeus.io/docs/stable/reference/linstorcluster/#specpatches) to remove this specific issue, but there might be more.

**Comment by junneyang** [comment]
> We generally only support v1.20 and up. You might be able to use a [`patch`](https://piraeus.io/docs/stable/reference/linstorcluster/#specpatches) to remove this specific issue, but there might be more.

求助，可以具体一点吗，就拿着个错误示例（.spec.ipFamilyPolicy）怎么 patch

**Comment by WanzenBug** [comment]
```yaml
...
spec:
  patches:
  - patch: |
      - op: remove
        path: /spec/ipFamilyPolicy
    target:
      kind: Service
      name: linstor-controller
```
