### ISSUE TITLE
[Feature Request] Global registry override for dark sites

### ISSUE THREAD

**Issue by alexzhc** [piraeusdatastore/piraeus-operator#84]
As there are quite a few images and registries in the value.yaml, it would be more convenient to have a global `registry override` for dark sites where a single intranet registry are usually employed to get job done. 

If below can be made possible (all of quay.io, docker.io, gcr.io registries are overridden)

`helm install piraeus-op piraeus/piraeus --global.registryOverride=myreg.io/piraeus`

**Comment by alexzhc** [comment]
A `--global.registryCredential` is also needed for security.

**Comment by WanzenBug** [comment]
I would prefer to use an approach similar to container resources: https://github.com/piraeusdatastore/piraeus-operator/blob/master/examples/resource-requirements.yaml

I.e. we provide another example config file:
```yaml
csi-snapshotter:
  image: private.example.com/piraeus/snapshot-controller:v2.1.0
csi:
  pluginImage: private.example.com/piraeus/piraeus-csi:v0.9.0
  csiAttacherImage: private.example.com/piraeus/csi-attacher:v2.2.0
  ...
```

That way I think it would be clearer what is happening. Also
* users are not bound to our exact naming convention
* We don't have to write a switch between default and override values on every use of the image

As for the registryCredential part:
This is something we should look into. Currently we use `drbdRepoCred`, which is:
* a bad name
* not used everywhere
